/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.sql.SQLException;
import logica.Vendedor;

/**
 *
 * @author Facultad
 */
public class agregarMotoViejo extends javax.swing.JPanel {
    Vendedor vendedor = new Vendedor();
    /**
     * Creates new form agregarAuto
     */
    public agregarMotoViejo(Vendedor vendedor1) {
        initComponents();
        this.vendedor = vendedor1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        contentMoto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        intKm = new javax.swing.JTextField();
        intPotencia = new javax.swing.JTextField();
        txtEmbrague = new javax.swing.JTextField();
        ssMarca = new javax.swing.JComboBox<>();
        botonNuevo = new javax.swing.JRadioButton();
        botonUsado = new javax.swing.JRadioButton();
        botonLimpiar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        intPasajeros = new javax.swing.JTextField();
        intPrecio = new javax.swing.JTextField();

        contentMoto.setBackground(new java.awt.Color(134, 182, 246));
        contentMoto.setPreferredSize(new java.awt.Dimension(560, 500));

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jLabel3.setText("Color");

        jLabel4.setText("Kilometros");

        jLabel5.setText("Condición");

        jLabel6.setText("Potencia");

        jLabel8.setText("Precio");

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        ssMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Honda", "Yamaha", "Rouser", "Motomel", "Harley Davidson" }));
        ssMarca.setToolTipText("Seleccione una Marca");
        ssMarca.setDoubleBuffered(true);
        ssMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssMarcaActionPerformed(evt);
            }
        });

        botonNuevo.setBackground(new java.awt.Color(134, 182, 246));
        buttonGroup1.add(botonNuevo);
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonUsado.setBackground(new java.awt.Color(134, 182, 246));
        buttonGroup1.add(botonUsado);
        botonUsado.setText("Usado");

        botonLimpiar.setText("Limpiar");
        botonLimpiar.setFocusPainted(false);
        botonLimpiar.setFocusable(false);
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAgregar.setText("Agregar");
        botonAgregar.setFocusPainted(false);
        botonAgregar.setFocusable(false);
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.setFocusPainted(false);
        botonVolver.setFocusable(false);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo de embrague");

        jLabel10.setText("Cantidad de pasajeros");

        javax.swing.GroupLayout contentMotoLayout = new javax.swing.GroupLayout(contentMoto);
        contentMoto.setLayout(contentMotoLayout);
        contentMotoLayout.setHorizontalGroup(
            contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentMotoLayout.createSequentialGroup()
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentMotoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentMotoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolver))
                    .addGroup(contentMotoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contentMotoLayout.createSequentialGroup()
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(43, 43, 43)
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ssMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtModelo)
                                        .addComponent(txtColor)
                                        .addComponent(intKm, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonNuevo)
                                    .addComponent(botonUsado)))
                            .addGroup(contentMotoLayout.createSequentialGroup()
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(54, 54, 54)
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmbrague, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        contentMotoLayout.setVerticalGroup(
            contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentMotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolver)
                .addGap(55, 55, 55)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ssMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(intKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(botonNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonUsado)
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(intPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(intPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmbrague, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(intPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregar)
                    .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonLimpiar)))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentMoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ssMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssMarcaActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        txtModelo.setText("");
        ssMarca.setSelectedIndex(0);
        txtColor.setText("");
        intKm.setText("");
        intPotencia.setText("");
        intPrecio.setText("");
        txtEmbrague.setText("");
        intPasajeros.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        publicarVehiculo lobby = new publicarVehiculo(vendedor);
        lobby.setSize(560,500);
        lobby.setLocation(0,0);
        contentMoto.removeAll();
        contentMoto.add(lobby);
        contentMoto.revalidate();
        contentMoto.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        try {
            String modelo = String.valueOf(txtModelo.getText());
            String marca = String.valueOf(ssMarca.getSelectedItem());
            String color = txtColor.getText();
            int kilometros = Integer.parseInt(intKm.getText());
            
            String cond;
            if(botonNuevo.isSelected() & kilometros == 0) {
                cond = "Nuevo";
            } else if (botonUsado.isSelected() & kilometros > 0){
                cond = "Usado";
            } else {
                cond = "";
            }
            double potenciaMotor = Double.parseDouble(((intPotencia.getText())));
            double precio = Double.parseDouble(intPrecio.getText());
            String embrague = txtEmbrague.getText();
            int pasajeros = Integer.parseInt(intPasajeros.getText());
            
            if(kilometros < 0 || potenciaMotor < 0 || precio < 0 || pasajeros < 0) {
                throw new IllegalArgumentException();
            }
            
            vendedor.agregarMoto(modelo, marca, color, kilometros, cond, potenciaMotor, precio, embrague, pasajeros, vendedor.getIdVendedor());        
        } catch (NumberFormatException e){
            
            System.out.println(e.getMessage());
            System.out.println("Valores numéricos incorrectos");
        } catch(IllegalArgumentException e){
            e.getMessage();
            System.out.println("Valores menores a cero");
        }
    }//GEN-LAST:event_botonAgregarActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JRadioButton botonNuevo;
    private javax.swing.JRadioButton botonUsado;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contentMoto;
    private javax.swing.JTextField intKm;
    private javax.swing.JTextField intPasajeros;
    private javax.swing.JTextField intPotencia;
    private javax.swing.JTextField intPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> ssMarca;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmbrague;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
