/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logica.Vendedor;

/**
 *
 * @author Augusto
 */
public class agregarMoto extends javax.swing.JFrame {
    Vendedor vendedor = new Vendedor();
    FuncionRepetida fun = new FuncionRepetida();
    /**
     * Creates new form agregarMoto
     */
    public agregarMoto(Vendedor vendedor1) {
        initComponents();
        this.vendedor = vendedor1;
        setLocationRelativeTo(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contentMoto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        intKm = new javax.swing.JTextField();
        intPotencia = new javax.swing.JTextField();
        txtEmbrague = new javax.swing.JTextField();
        ssMarca = new javax.swing.JComboBox<>();
        botonNuevo = new javax.swing.JRadioButton();
        botonUsado = new javax.swing.JRadioButton();
        botonLimpiar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        intPasajeros = new javax.swing.JTextField();
        intPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        contentMoto.setBackground(new java.awt.Color(25, 69, 113));
        contentMoto.setPreferredSize(new java.awt.Dimension(560, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 192, 192));
        jLabel1.setText("Marca");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(192, 192, 192));
        jLabel2.setText("Modelo");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setText("Color");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(192, 192, 192));
        jLabel4.setText("Kilometros");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(192, 192, 192));
        jLabel5.setText("Condición");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(192, 192, 192));
        jLabel6.setText("Potencia");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(192, 192, 192));
        jLabel8.setText("Precio");

        txtModelo.setBackground(new java.awt.Color(192, 192, 192));
        txtModelo.setForeground(new java.awt.Color(0, 51, 102));

        txtColor.setBackground(new java.awt.Color(192, 192, 192));
        txtColor.setForeground(new java.awt.Color(0, 51, 102));
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        intKm.setBackground(new java.awt.Color(192, 192, 192));
        intKm.setForeground(new java.awt.Color(0, 51, 102));

        intPotencia.setBackground(new java.awt.Color(192, 192, 192));
        intPotencia.setForeground(new java.awt.Color(0, 51, 102));

        txtEmbrague.setBackground(new java.awt.Color(192, 192, 192));
        txtEmbrague.setForeground(new java.awt.Color(0, 51, 102));

        ssMarca.setBackground(new java.awt.Color(192, 192, 192));
        ssMarca.setForeground(new java.awt.Color(0, 51, 102));
        ssMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Honda", "Yamaha", "Rouser", "Motomel", "Harley Davidson" }));
        ssMarca.setToolTipText("Seleccione una Marca");
        ssMarca.setDoubleBuffered(true);
        ssMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssMarcaActionPerformed(evt);
            }
        });

        botonNuevo.setBackground(new java.awt.Color(25, 69, 113));
        botonNuevo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonNuevo.setForeground(new java.awt.Color(192, 192, 192));
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonUsado.setBackground(new java.awt.Color(25, 69, 113));
        botonUsado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonUsado.setForeground(new java.awt.Color(192, 192, 192));
        botonUsado.setText("Usado");

        botonLimpiar.setBackground(new java.awt.Color(192, 192, 192));
        botonLimpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonLimpiar.setForeground(new java.awt.Color(0, 51, 102));
        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLimpiar.setFocusPainted(false);
        botonLimpiar.setFocusable(false);
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAgregar.setBackground(new java.awt.Color(192, 192, 192));
        botonAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(0, 51, 102));
        botonAgregar.setText("AGREGAR");
        botonAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAgregar.setFocusPainted(false);
        botonAgregar.setFocusable(false);
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(192, 192, 192));
        jLabel9.setText("Tipo de embrague");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(192, 192, 192));
        jLabel10.setText("Cantidad de pasajeros");

        intPasajeros.setBackground(new java.awt.Color(192, 192, 192));
        intPasajeros.setForeground(new java.awt.Color(0, 51, 102));

        intPrecio.setBackground(new java.awt.Color(192, 192, 192));
        intPrecio.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout contentMotoLayout = new javax.swing.GroupLayout(contentMoto);
        contentMoto.setLayout(contentMotoLayout);
        contentMotoLayout.setHorizontalGroup(
            contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentMotoLayout.createSequentialGroup()
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentMotoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contentMotoLayout.createSequentialGroup()
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(112, 112, 112)
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ssMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtModelo)
                                        .addComponent(txtColor)
                                        .addComponent(intKm, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonNuevo)
                                    .addComponent(botonUsado)))
                            .addGroup(contentMotoLayout.createSequentialGroup()
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(54, 54, 54)
                                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmbrague, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(contentMotoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentMotoLayout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        contentMotoLayout.setVerticalGroup(
            contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentMotoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ssMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(intKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentMotoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonUsado))
                    .addGroup(contentMotoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(intPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(intPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmbrague, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(intPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(contentMotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregar)
                    .addComponent(botonLimpiar))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentMoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void ssMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssMarcaActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        txtModelo.setText("");
        ssMarca.setSelectedIndex(0);
        txtColor.setText("");
        intKm.setText("");
        intPotencia.setText("");
        intPrecio.setText("");
        txtEmbrague.setText("");
        intPasajeros.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        try {
            String modelo = String.valueOf(txtModelo.getText());
            String marca = String.valueOf(ssMarca.getSelectedItem());
            String color = txtColor.getText();
            int kilometros = Integer.parseInt(intKm.getText());

            String cond;
             if(botonNuevo.isSelected() & kilometros == 0) {
                cond = "Nuevo";
            } else if (botonUsado.isSelected() & kilometros > 0){
                cond = "Usado";
            } else if (botonNuevo.isSelected() & kilometros != 0){
                cond = "Usado";
            } else if (botonUsado.isSelected() & kilometros == 0){
                cond = "Nuevo";
            } else {
                cond = "";
            }
            double potenciaMotor = Double.parseDouble(((intPotencia.getText())));
            double precio = Double.parseDouble(intPrecio.getText());
            String embrague = txtEmbrague.getText();
            int pasajeros = Integer.parseInt(intPasajeros.getText());

            if(kilometros < 0 || potenciaMotor < 0 || precio < 0 || pasajeros < 0) {
                throw new IllegalArgumentException();
            }

            vendedor.agregarMoto(modelo, marca, color, kilometros, cond, potenciaMotor, precio, embrague, pasajeros, vendedor.getIdVendedor());
            fun.mostrarMensaje("Vehiculo publicado con exito", "Info", "VEHICULO PUBLICADO");
        } catch (NumberFormatException e){
            fun.mostrarMensaje("Valores incorrectos", "Error", "VEHICULO NO PUBLICADO");
        } catch(IllegalArgumentException e){
            e.getMessage();
            fun.mostrarMensaje("Valores menores a cero", "Error", "VEHICULO NO PUBLICADO");
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JRadioButton botonNuevo;
    private javax.swing.JRadioButton botonUsado;
    private javax.swing.JPanel contentMoto;
    private javax.swing.JTextField intKm;
    private javax.swing.JTextField intPasajeros;
    private javax.swing.JTextField intPotencia;
    private javax.swing.JTextField intPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> ssMarca;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmbrague;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
