/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logica.Vendedor;

/**
 *
 * @author Augusto
 */
public class agregarCamioneta extends javax.swing.JFrame {
    Vendedor vendedor = new Vendedor();
    FuncionRepetida fun = new FuncionRepetida();
    /**
     * Creates new form agregarCamioneta
     */
    public agregarCamioneta(Vendedor vendedor1) {
        initComponents();
        this.vendedor = vendedor1;
        setLocationRelativeTo(null);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentCamioneta7 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        intKm = new javax.swing.JTextField();
        intPotencia = new javax.swing.JTextField();
        intPrecio = new javax.swing.JTextField();
        ssMarca = new javax.swing.JComboBox<>();
        botonNuevo = new javax.swing.JRadioButton();
        botonUsado = new javax.swing.JRadioButton();
        botonLimpiar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        txtTraccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(134, 182, 246));
        setPreferredSize(new java.awt.Dimension(560, 500));
        setResizable(false);

        contentCamioneta7.setBackground(new java.awt.Color(25, 69, 113));
        contentCamioneta7.setPreferredSize(new java.awt.Dimension(560, 500));

        jLabel57.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(192, 192, 192));
        jLabel57.setText("Marca");

        jLabel58.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(192, 192, 192));
        jLabel58.setText("Modelo");

        jLabel59.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(192, 192, 192));
        jLabel59.setText("Color");

        jLabel60.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(192, 192, 192));
        jLabel60.setText("Kilometros");

        jLabel61.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(192, 192, 192));
        jLabel61.setText("Condición");

        jLabel62.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(192, 192, 192));
        jLabel62.setText("Potencia");

        jLabel63.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(192, 192, 192));
        jLabel63.setText("Precio");

        txtModelo.setBackground(new java.awt.Color(192, 192, 192));
        txtModelo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(0, 51, 102));

        txtColor.setBackground(new java.awt.Color(192, 192, 192));
        txtColor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtColor.setForeground(new java.awt.Color(0, 51, 102));
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        intKm.setBackground(new java.awt.Color(192, 192, 192));
        intKm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        intKm.setForeground(new java.awt.Color(0, 51, 102));

        intPotencia.setBackground(new java.awt.Color(192, 192, 192));
        intPotencia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        intPotencia.setForeground(new java.awt.Color(0, 51, 102));

        intPrecio.setBackground(new java.awt.Color(192, 192, 192));
        intPrecio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        intPrecio.setForeground(new java.awt.Color(0, 51, 102));

        ssMarca.setBackground(new java.awt.Color(192, 192, 192));
        ssMarca.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        ssMarca.setForeground(new java.awt.Color(0, 51, 102));
        ssMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Chevrolet", "Ford", "Nissan", "Toyota", "Volkswagen" }));
        ssMarca.setToolTipText("Seleccione una Marca");
        ssMarca.setDoubleBuffered(true);
        ssMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssMarcaActionPerformed(evt);
            }
        });

        botonNuevo.setBackground(new java.awt.Color(25, 69, 113));
        botonNuevo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonNuevo.setForeground(new java.awt.Color(192, 192, 192));
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonUsado.setBackground(new java.awt.Color(25, 69, 113));
        botonUsado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonUsado.setForeground(new java.awt.Color(192, 192, 192));
        botonUsado.setText("Usado");

        botonLimpiar.setBackground(new java.awt.Color(192, 192, 192));
        botonLimpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonLimpiar.setForeground(new java.awt.Color(0, 51, 102));
        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLimpiar.setFocusPainted(false);
        botonLimpiar.setFocusable(false);
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAgregar.setBackground(new java.awt.Color(192, 192, 192));
        botonAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(0, 51, 102));
        botonAgregar.setText("AGREGAR");
        botonAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAgregar.setFocusPainted(false);
        botonAgregar.setFocusable(false);
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(192, 192, 192));
        jLabel64.setText("Tipo de Traccion ");

        txtTraccion.setBackground(new java.awt.Color(192, 192, 192));
        txtTraccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtTraccion.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout contentCamioneta7Layout = new javax.swing.GroupLayout(contentCamioneta7);
        contentCamioneta7.setLayout(contentCamioneta7Layout);
        contentCamioneta7Layout.setHorizontalGroup(
            contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentCamioneta7Layout.createSequentialGroup()
                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentCamioneta7Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contentCamioneta7Layout.createSequentialGroup()
                                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel57)
                                    .addComponent(jLabel58)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel60)
                                    .addComponent(jLabel61))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ssMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtModelo)
                                    .addComponent(txtColor)
                                    .addComponent(intKm, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonNuevo)
                                    .addComponent(botonUsado)))
                            .addGroup(contentCamioneta7Layout.createSequentialGroup()
                                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel64))
                                .addGap(54, 54, 54)
                                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(contentCamioneta7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        contentCamioneta7Layout.setVerticalGroup(
            contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentCamioneta7Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentCamioneta7Layout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel58)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel59)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentCamioneta7Layout.createSequentialGroup()
                        .addComponent(ssMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(intKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentCamioneta7Layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonUsado))
                    .addGroup(contentCamioneta7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel61)))
                .addGap(16, 16, 16)
                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(intPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(intPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(txtTraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(contentCamioneta7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiar)
                    .addComponent(botonAgregar))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentCamioneta7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentCamioneta7, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        try {
            String modelo = String.valueOf(txtModelo.getText());
            String marca = String.valueOf(ssMarca.getSelectedItem());
            String color = txtColor.getText();
            int kilometros = Integer.parseInt(intKm.getText());

            String cond;
            if(botonNuevo.isSelected() & kilometros == 0) {
                cond = "Nuevo";
            } else if (botonUsado.isSelected() & kilometros > 0){
                cond = "Usado";
            } else if (botonNuevo.isSelected() & kilometros != 0){
                cond = "Usado";
            } else if (botonUsado.isSelected() & kilometros == 0){
                cond = "Nuevo";
            } else {
                cond = "";
            }
            double potenciaMotor = Double.parseDouble(((intPotencia.getText())));
            double precio = Double.parseDouble(intPrecio.getText());
            String traccion = String.valueOf(txtTraccion.getText());

            if(kilometros < 0 || potenciaMotor < 0 || precio < 0) {
                throw new IllegalArgumentException();
            }
            vendedor.agregarCamioneta(modelo, marca, color, kilometros, cond, potenciaMotor, precio, traccion, vendedor.getIdVendedor());
            
            fun.mostrarMensaje("Vehiculo publicado con exito", "Info", "VEHICULO PUBLICADO");
        } catch (NumberFormatException e){
            fun.mostrarMensaje("Valores incorrectos", "Error", "VEHICULO NO PUBLICADO");
        } catch(IllegalArgumentException e){
            e.getMessage();
            fun.mostrarMensaje("Valores menores a cero", "Error", "VEHICULO NO PUBLICADO");
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        txtModelo.setText("");
        ssMarca.setSelectedIndex(0);
        txtColor.setText("");
        intKm.setText("");
        intPotencia.setText("");
        intPrecio.setText("");
        txtTraccion.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void ssMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssMarcaActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JRadioButton botonNuevo;
    private javax.swing.JRadioButton botonUsado;
    private javax.swing.JPanel contentCamioneta7;
    private javax.swing.JTextField intKm;
    private javax.swing.JTextField intPotencia;
    private javax.swing.JTextField intPrecio;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JComboBox<String> ssMarca;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtTraccion;
    // End of variables declaration//GEN-END:variables
}
