/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.Cliente;
import logica.Vendedor;

/**
 *
 * @author PROGRAMAR
 */
public class buscarVehiculoCliente extends javax.swing.JPanel {
    Vendedor vendedor = new Vendedor();
    Cliente cliente = new Cliente();
    private TableRowSorter trsfiltro;
    /**
     * Creates new form buscarVehiculoCliente
     * @param cliente
     */
    public buscarVehiculoCliente(Cliente cliente) {
        initComponents();
        mostrar("Vehiculos");
        this.cliente = cliente;
        trsfiltro = new TableRowSorter<>(tablaBuscar.getModel());
        tablaBuscar.setRowSorter(trsfiltro);
        campoFiltro.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(final KeyEvent e) {
        String cadena = (campoFiltro.getText());
        campoFiltro.setText(cadena);
        repaint();
        filtro();
        }
        });
    }

    public void mostrar(String tabla) {
        List<String[]> vehiculos = vendedor.mostrarVehiculosClientes(tabla);

        DefaultTableModel model = new DefaultTableModel();
 
        model.addColumn("Marca");
        model.addColumn("Modelo");
        model.addColumn("Condición");
        model.addColumn("Tipo");


        for (String[] vehiculo : vehiculos) {
            model.addRow(vehiculo);
        }

        tablaBuscar.setModel(model);

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contentBuscar = new javax.swing.JPanel();
        cabecera = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contentFiltros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscar = new javax.swing.JTable();
        tipoFiltro = new javax.swing.JComboBox<>();
        campoFiltro = new javax.swing.JTextField();

        contentBuscar.setBackground(new java.awt.Color(0, 51, 102));
        contentBuscar.setForeground(new java.awt.Color(192, 192, 192));

        cabecera.setBackground(new java.awt.Color(0, 51, 102));
        cabecera.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        cabecera.setForeground(new java.awt.Color(192, 192, 192));
        cabecera.setText("BÚSQUEDA");

        jSeparator1.setForeground(new java.awt.Color(192, 192, 192));

        contentFiltros.setBackground(new java.awt.Color(102, 204, 255));

        tablaBuscar.setBackground(new java.awt.Color(192, 192, 192));
        tablaBuscar.setForeground(new java.awt.Color(0, 51, 102));
        tablaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Marca", "Modelo", "Condicion", "Kms"
            }
        ));
        jScrollPane1.setViewportView(tablaBuscar);

        javax.swing.GroupLayout contentFiltrosLayout = new javax.swing.GroupLayout(contentFiltros);
        contentFiltros.setLayout(contentFiltrosLayout);
        contentFiltrosLayout.setHorizontalGroup(
            contentFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        contentFiltrosLayout.setVerticalGroup(
            contentFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        tipoFiltro.setBackground(new java.awt.Color(192, 192, 192));
        tipoFiltro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tipoFiltro.setForeground(new java.awt.Color(25, 69, 113));
        tipoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca", "Modelo", "Condicion", "Tipo" }));
        tipoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFiltroActionPerformed(evt);
            }
        });

        campoFiltro.setBackground(new java.awt.Color(192, 192, 192));
        campoFiltro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        campoFiltro.setForeground(new java.awt.Color(25, 69, 113));
        campoFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoFiltroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout contentBuscarLayout = new javax.swing.GroupLayout(contentBuscar);
        contentBuscar.setLayout(contentBuscarLayout);
        contentBuscarLayout.setHorizontalGroup(
            contentBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(contentFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentBuscarLayout.createSequentialGroup()
                        .addComponent(tipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentBuscarLayout.setVerticalGroup(
            contentBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(contentFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoFiltroKeyTyped
         filtro();

    }//GEN-LAST:event_campoFiltroKeyTyped

    private void tipoFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoFiltroActionPerformed

    public void filtro() {
       String textoFiltro = campoFiltro.getText();
    
    if (textoFiltro.trim().length() == 0) {
        // Si el campo de texto está vacío, remover el filtro
        trsfiltro.setRowFilter(null);
    } else {
        // Aplicar el filtro insensible a mayúsculas/minúsculas en la columna seleccionada
        trsfiltro.setRowFilter(RowFilter.regexFilter("(?i)" + textoFiltro, tipoFiltro.getSelectedIndex()));
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cabecera;
    private javax.swing.JTextField campoFiltro;
    private javax.swing.JPanel contentBuscar;
    private javax.swing.JPanel contentFiltros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaBuscar;
    private javax.swing.JComboBox<String> tipoFiltro;
    // End of variables declaration//GEN-END:variables
}
