/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Cliente;
import persistance.validarInicio;

/**
 *
 * @author PROGRAMAR
 */
public class inicioCliente extends javax.swing.JPanel {
    FuncionRepetida fun = new FuncionRepetida();
    /**
     * Creates new form inicioCliente
     */
    public inicioCliente() {
        initComponents();
    }
    public void showLobbyCliente(Cliente cliente){
        lobbyCliente lobby = new lobbyCliente(cliente);
        lobby.setSize(800,500);
        lobby.setLocation(0,0);
        contentCliente.removeAll();
        contentCliente.add(lobby);
        contentCliente.revalidate();
        contentCliente.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentCliente = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        botonIngresarCliente = new javax.swing.JButton();
        botonVolverInicio = new javax.swing.JButton();
        campoContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        contentCliente.setBackground(new java.awt.Color(245, 230, 210));
        contentCliente.setForeground(new java.awt.Color(0, 51, 102));

        campoUsuario.setBackground(new java.awt.Color(245, 230, 210));
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText("Ingrese su usuario");
        campoUsuario.setBorder(null);
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoUsuarioMousePressed(evt);
            }
        });
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        botonIngresarCliente.setBackground(new java.awt.Color(0, 51, 102));
        botonIngresarCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        botonIngresarCliente.setForeground(new java.awt.Color(192, 192, 192));
        botonIngresarCliente.setText("Ingresar");
        botonIngresarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        botonIngresarCliente.setFocusPainted(false);
        botonIngresarCliente.setFocusable(false);
        botonIngresarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIngresarClienteMousePressed(evt);
            }
        });
        botonIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarClienteActionPerformed(evt);
            }
        });

        botonVolverInicio.setBackground(new java.awt.Color(0, 51, 102));
        botonVolverInicio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        botonVolverInicio.setForeground(new java.awt.Color(192, 192, 192));
        botonVolverInicio.setText("Volver");
        botonVolverInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), java.awt.Color.white, new java.awt.Color(0, 51, 102), new java.awt.Color(192, 192, 192)));
        botonVolverInicio.setFocusPainted(false);
        botonVolverInicio.setFocusable(false);
        botonVolverInicio.setPreferredSize(new java.awt.Dimension(40, 25));
        botonVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInicioActionPerformed(evt);
            }
        });

        campoContraseña.setBackground(new java.awt.Color(245, 230, 210));
        campoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseña.setText("***************");
        campoContraseña.setBorder(null);
        campoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoContraseñaMousePressed(evt);
            }
        });
        campoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseñaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));

        jSeparator3.setForeground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 230, 210));
        jLabel1.setText("C\nU\nY\nO\nM\nO\nT\nO\nR\nS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("INICIO SESIÓN CLIENTE");

        javax.swing.GroupLayout contentClienteLayout = new javax.swing.GroupLayout(contentCliente);
        contentCliente.setLayout(contentClienteLayout);
        contentClienteLayout.setHorizontalGroup(
            contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentClienteLayout.createSequentialGroup()
                .addGroup(contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentClienteLayout.createSequentialGroup()
                        .addContainerGap(117, Short.MAX_VALUE)
                        .addGroup(contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                .addComponent(jSeparator2)
                                .addComponent(campoUsuario)
                                .addComponent(jSeparator3)))
                        .addGap(133, 133, 133))
                    .addGroup(contentClienteLayout.createSequentialGroup()
                        .addGroup(contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentClienteLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(botonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentClienteLayout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(botonIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentClienteLayout.setVerticalGroup(
            contentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentClienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botonIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contentCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInicioActionPerformed
        inicio lobby = new inicio();
        lobby.setSize(800,500);
        lobby.setLocation(0,0);
        contentCliente.removeAll();
        contentCliente.add(lobby);
        contentCliente.revalidate();
        contentCliente.repaint();
    }//GEN-LAST:event_botonVolverInicioActionPerformed

    private void botonIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarClienteActionPerformed

        //obtencion de los datos a validar
        String usuario = campoUsuario.getText();
        String contrasena = new String(campoContraseña.getPassword());
        validarInicio validador = new validarInicio();
        try {
            //condicional para mostrar el lobby en caso de que el login sea exitoso
            if(validador.validarCliente(usuario, contrasena)){
                Cliente cliente = new Cliente();
                cliente.setUsuario(usuario);
                cliente.setContrasena(contrasena);
                int idCliente = validador.traerIdCliente(usuario);
                cliente.setIdCliente(idCliente);
                showLobbyCliente(cliente);
            } else {
                fun.mostrarMensaje("Usuario o contraseña incorrectos", "Error", "Error");
            }
        } catch (SQLException ex) {
            Logger.getLogger(inicioGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonIngresarClienteActionPerformed

    private void botonIngresarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarClienteMousePressed

    }//GEN-LAST:event_botonIngresarClienteMousePressed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMousePressed
        if(campoUsuario.getText().equals("Ingrese su usuario")){
            campoUsuario.setText("");
            campoUsuario.setForeground(Color.black);
        }
        if(String.valueOf(campoContraseña.getPassword()).isEmpty() ){
            campoContraseña.setText("***************");
            campoContraseña.setForeground(Color.gray);
        }        
    }//GEN-LAST:event_campoUsuarioMousePressed

    private void campoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraseñaActionPerformed

    private void campoContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraseñaMousePressed
        if(String.valueOf(campoContraseña.getPassword()).equals("***************")){
            campoContraseña.setText("");
            campoContraseña.setForeground(Color.black);
        }
        if(campoUsuario.getText().isEmpty()){
            campoUsuario.setText("Ingrese su usuario");
            campoUsuario.setForeground(Color.gray);   
        }
        
    }//GEN-LAST:event_campoContraseñaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresarCliente;
    private javax.swing.JButton botonVolverInicio;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JPanel contentCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
