/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import javax.swing.ImageIcon;

/**
 *
 * @author PROGRAMAR
 */
public class inicio extends javax.swing.JPanel {

    /**
     * Creates new form inicio
     */
    public inicio() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        contentInicio = new javax.swing.JPanel();
        botonVendedor = new javax.swing.JButton();
        botonCliente = new javax.swing.JButton();
        botonGerente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logofondo = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));

        contentInicio.setBackground(new java.awt.Color(0, 51, 102));
        contentInicio.setPreferredSize(new java.awt.Dimension(1024, 640));

        botonVendedor.setBackground(new java.awt.Color(25, 69, 113));
        botonVendedor.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        botonVendedor.setForeground(new java.awt.Color(192, 192, 192));
        botonVendedor.setText("VENDEDOR");
        botonVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonVendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVendedor.setFocusPainted(false);
        botonVendedor.setFocusable(false);
        botonVendedor.setPreferredSize(new java.awt.Dimension(75, 35));
        botonVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVendedorActionPerformed(evt);
            }
        });

        botonCliente.setBackground(new java.awt.Color(25, 69, 113));
        botonCliente.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        botonCliente.setForeground(new java.awt.Color(192, 192, 192));
        botonCliente.setText("CLIENTE");
        botonCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCliente.setFocusPainted(false);
        botonCliente.setFocusable(false);
        botonCliente.setPreferredSize(new java.awt.Dimension(75, 35));
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });

        botonGerente.setBackground(new java.awt.Color(25, 69, 113));
        botonGerente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        botonGerente.setForeground(new java.awt.Color(192, 192, 192));
        botonGerente.setText("GERENTE");
        botonGerente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonGerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGerente.setFocusPainted(false);
        botonGerente.setFocusable(false);
        botonGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGerenteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 192, 192));
        jLabel1.setText("BIENVENIDO");

        logofondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrea\\Desktop\\ConcesionarioFinal\\src\\main\\java\\views\\FONDO.png")); // NOI18N

        javax.swing.GroupLayout contentInicioLayout = new javax.swing.GroupLayout(contentInicio);
        contentInicio.setLayout(contentInicioLayout);
        contentInicioLayout.setHorizontalGroup(
            contentInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentInicioLayout.createSequentialGroup()
                .addGroup(contentInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentInicioLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(contentInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonGerente, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                    .addGroup(contentInicioLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(logofondo)
                .addGap(79, 79, 79))
        );
        contentInicioLayout.setVerticalGroup(
            contentInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentInicioLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(botonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botonVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botonGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentInicioLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(logofondo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVendedorActionPerformed
       inicioVendedor inicio = new inicioVendedor();
       inicio.setSize(800,500);
       inicio.setLocation(0,0);
       contentInicio.removeAll();
       contentInicio.add(inicio);
       contentInicio.revalidate();
       contentInicio.repaint();
    }//GEN-LAST:event_botonVendedorActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
       inicioCliente inicio = new inicioCliente();
       inicio.setSize(800,500);
       inicio.setLocation(0,0);
       contentInicio.removeAll();
       contentInicio.add(inicio);
       contentInicio.revalidate();
       contentInicio.repaint();
    }//GEN-LAST:event_botonClienteActionPerformed

    private void botonGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGerenteActionPerformed
       inicioGerente inicio = new inicioGerente();
       inicio.setSize(800,500);
       inicio.setLocation(0,0);
       contentInicio.removeAll();
       contentInicio.add(inicio);
       contentInicio.revalidate();
       contentInicio.repaint();
    }//GEN-LAST:event_botonGerenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton botonGerente;
    private javax.swing.JButton botonVendedor;
    private javax.swing.JPanel contentInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel logofondo;
    // End of variables declaration//GEN-END:variables
}
