/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Gerente;
import persistance.validarInicio;

/**
 *
 * @author PROGRAMAR
 */
public class inicioGerente extends javax.swing.JPanel {
    FuncionRepetida fun = new FuncionRepetida();
    /**
     * Creates new form inicioGerente
     */
    public inicioGerente() {
        
        initComponents();
    }
    
    public void showLobbyGerente(){
        lobbyGerente lobby = new lobbyGerente();
        lobby.setSize(800,500);
        lobby.setLocation(0,0);
        contentGerente.removeAll();
        contentGerente.add(lobby);
        contentGerente.revalidate();
        contentGerente.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        contentGerente = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        botonIngresarGerente = new javax.swing.JButton();
        botonVolverInicio = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        campoContraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("INICIO SESIÓN CLIENTE");

        contentGerente.setBackground(new java.awt.Color(245, 230, 210));
        contentGerente.setForeground(new java.awt.Color(0, 51, 102));

        campoUsuario.setBackground(new java.awt.Color(245, 230, 210));
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText("Ingrese su usuario");
        campoUsuario.setBorder(null);
        campoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoUsuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoUsuarioMousePressed(evt);
            }
        });
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        botonIngresarGerente.setBackground(new java.awt.Color(0, 51, 102));
        botonIngresarGerente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        botonIngresarGerente.setForeground(new java.awt.Color(245, 230, 210));
        botonIngresarGerente.setText("Ingresar");
        botonIngresarGerente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonIngresarGerente.setPreferredSize(new java.awt.Dimension(49, 22));
        botonIngresarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarGerenteActionPerformed(evt);
            }
        });

        botonVolverInicio.setBackground(new java.awt.Color(0, 51, 102));
        botonVolverInicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        botonVolverInicio.setForeground(new java.awt.Color(245, 230, 210));
        botonVolverInicio.setText("Volver");
        botonVolverInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        botonVolverInicio.setPreferredSize(new java.awt.Dimension(40, 25));
        botonVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInicioActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));

        campoContraseña.setBackground(new java.awt.Color(245, 230, 210));
        campoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseña.setText("***************");
        campoContraseña.setBorder(null);
        campoContraseña.setPreferredSize(new java.awt.Dimension(64, 16));
        campoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoContraseñaMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 230, 210));
        jLabel1.setText("C\nU\nY\nO\nM\nO\nT\nO\nR\nS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("INICIO SESIÓN GERENTE");

        javax.swing.GroupLayout contentGerenteLayout = new javax.swing.GroupLayout(contentGerente);
        contentGerente.setLayout(contentGerenteLayout);
        contentGerenteLayout.setHorizontalGroup(
            contentGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentGerenteLayout.createSequentialGroup()
                .addGroup(contentGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentGerenteLayout.createSequentialGroup()
                        .addContainerGap(129, Short.MAX_VALUE)
                        .addGroup(contentGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))
                    .addGroup(contentGerenteLayout.createSequentialGroup()
                        .addGroup(contentGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentGerenteLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(botonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentGerenteLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(botonIngresarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentGerenteLayout.setVerticalGroup(
            contentGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentGerenteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botonIngresarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInicioActionPerformed
        inicio lobby = new inicio();
        lobby.setSize(800,500);
        lobby.setLocation(0,0);
        contentGerente.removeAll();
        contentGerente.add(lobby);
        contentGerente.revalidate();
        contentGerente.repaint();
    }//GEN-LAST:event_botonVolverInicioActionPerformed

    private void botonIngresarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarGerenteActionPerformed


        //obtencion de los datos a validar
        String usuario = campoUsuario.getText();
        String contrasena = new String(campoContraseña.getPassword());
        String tipo = "Gerente";
        validarInicio validador = new validarInicio();
        try {
            //condicional para mostrar el lobby en caso de que el login sea exitoso
            if(validador.validarEmpleado(usuario, contrasena, tipo)){
                showLobbyGerente();
            } else {
                fun.mostrarMensaje("Usuario o contraseña incorrectos", "Error", "Error");
            }
        } catch (SQLException ex) {
            Logger.getLogger(inicioGerente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonIngresarGerenteActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMousePressed
        
        if(campoUsuario.getText().equals("Ingrese su usuario")){
            campoUsuario.setText("");
            campoUsuario.setForeground(Color.black);
        }
        if(String.valueOf(campoContraseña.getPassword()).isEmpty() ){
            campoContraseña.setText("***************");
            campoContraseña.setForeground(Color.gray);
        }  
        
    }//GEN-LAST:event_campoUsuarioMousePressed

    private void campoContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraseñaMousePressed
        
        if(String.valueOf(campoContraseña.getPassword()).equals("***************")){
            campoContraseña.setText("");
            campoContraseña.setForeground(Color.black);
        }
        if(campoUsuario.getText().isEmpty()){
            campoUsuario.setText("Ingrese su usuario");
            campoUsuario.setForeground(Color.gray);   
        }
        
        
    }//GEN-LAST:event_campoContraseñaMousePressed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresarGerente;
    private javax.swing.JButton botonVolverInicio;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JPanel contentGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
