/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Vendedor;
import persistance.validarInicio;
//import persistance.validarInicio;

/**
 *
 * @author PROGRAMAR
 */
public class inicioVendedor extends javax.swing.JPanel {
    FuncionRepetida fun = new FuncionRepetida();
    /**
     * Creates new form inicioVendedor
     */
    public inicioVendedor() {
        initComponents();
    }

    public void showLobbyVendedor(Vendedor vendedor){
        lobbyVendedor lobby = new lobbyVendedor(vendedor);
        lobby.setSize(800,500);
        lobby.setLocation(0,0);
        contentVendedor1.removeAll();
        contentVendedor1.add(lobby);
        contentVendedor1.revalidate();
        contentVendedor1.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        contentVendedor1 = new javax.swing.JPanel();
        campoUsuario = new javax.swing.JTextField();
        botonIngresarVendedor1 = new javax.swing.JButton();
        botonVolverInicio1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        campoContraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("INICIO SESIÓN VENDEDOR");

        contentVendedor1.setBackground(new java.awt.Color(245, 230, 210));
        contentVendedor1.setPreferredSize(new java.awt.Dimension(800, 500));

        campoUsuario.setBackground(new java.awt.Color(245, 230, 210));
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText("Ingrese su usuario");
        campoUsuario.setBorder(null);
        campoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoUsuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoUsuarioMousePressed(evt);
            }
        });
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        botonIngresarVendedor1.setBackground(new java.awt.Color(0, 51, 102));
        botonIngresarVendedor1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonIngresarVendedor1.setForeground(new java.awt.Color(245, 230, 210));
        botonIngresarVendedor1.setText("Ingresar");
        botonIngresarVendedor1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        botonIngresarVendedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarVendedor1ActionPerformed(evt);
            }
        });

        botonVolverInicio1.setBackground(new java.awt.Color(0, 51, 102));
        botonVolverInicio1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonVolverInicio1.setForeground(new java.awt.Color(245, 230, 210));
        botonVolverInicio1.setText("Volver");
        botonVolverInicio1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        botonVolverInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInicio1ActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 51, 102));

        jSeparator6.setForeground(new java.awt.Color(0, 51, 102));

        campoContraseña.setBackground(new java.awt.Color(245, 230, 210));
        campoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseña.setText("***************");
        campoContraseña.setBorder(null);
        campoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoContraseñaMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 230, 210));
        jLabel1.setText("C\nU\nY\nO\nM\nO\nT\nO\nR\nS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("INICIO SESIÓN VENDEDOR");

        javax.swing.GroupLayout contentVendedor1Layout = new javax.swing.GroupLayout(contentVendedor1);
        contentVendedor1.setLayout(contentVendedor1Layout);
        contentVendedor1Layout.setHorizontalGroup(
            contentVendedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentVendedor1Layout.createSequentialGroup()
                .addGroup(contentVendedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentVendedor1Layout.createSequentialGroup()
                        .addContainerGap(117, Short.MAX_VALUE)
                        .addGroup(contentVendedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentVendedor1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(botonIngresarVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentVendedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator5)
                                .addComponent(campoUsuario)
                                .addComponent(campoContraseña)
                                .addComponent(jSeparator6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(133, 133, 133))
                    .addGroup(contentVendedor1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(botonVolverInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentVendedor1Layout.setVerticalGroup(
            contentVendedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentVendedor1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonVolverInicio1)
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(botonIngresarVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVendedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVendedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void botonIngresarVendedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarVendedor1ActionPerformed
        
        
        //obtencion de los datos a validar
        String usuario = campoUsuario.getText();
        String contrasena = new String(campoContraseña.getPassword());
        String tipo = "Vendedor";
        validarInicio validador = new validarInicio();
        try {
            //condicional para mostrar el lobby en caso de que el login sea exitoso
            if(validador.validarEmpleado(usuario, contrasena, tipo)){
                Vendedor vendedor = new Vendedor();
                vendedor.setUsuario(usuario);
                vendedor.setContrasena(contrasena);
                int idVendedor = validador.traerIdVendedor(usuario);
                vendedor.setIdVendedor(idVendedor);
                
                showLobbyVendedor(vendedor);
            } else {
                fun.mostrarMensaje("Usuario o contraseña incorrectos", "Error", "Error");
            }
        } catch (SQLException ex) {
            Logger.getLogger(inicioGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonIngresarVendedor1ActionPerformed

    private void botonVolverInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInicio1ActionPerformed
        inicio lobby = new inicio();
        lobby.setSize(800,500);
        lobby.setLocation(0,0);
        contentVendedor1.removeAll();
        contentVendedor1.add(lobby);
        contentVendedor1.revalidate();
        contentVendedor1.repaint();
    }//GEN-LAST:event_botonVolverInicio1ActionPerformed

    private void campoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMousePressed
        if(campoUsuario.getText().equals("Ingrese su usuario")){
            campoUsuario.setText("");
            campoUsuario.setForeground(Color.black);
        }
        if(String.valueOf(campoContraseña.getPassword()).isEmpty() ){
            campoContraseña.setText("***************");
            campoContraseña.setForeground(Color.gray);
        }  
    }//GEN-LAST:event_campoUsuarioMousePressed

    private void campoContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraseñaMousePressed
        
        if(String.valueOf(campoContraseña.getPassword()).equals("***************")){
            campoContraseña.setText("");
            campoContraseña.setForeground(Color.black);
        }
        if(campoUsuario.getText().isEmpty()){
            campoUsuario.setText("Ingrese su usuario");
            campoUsuario.setForeground(Color.gray);   
        }
        
    }//GEN-LAST:event_campoContraseñaMousePressed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresarVendedor1;
    private javax.swing.JButton botonVolverInicio1;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JPanel contentVendedor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
