/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import logica.Cliente;


/**
 *
 * @author PROGRAMAR
 */
public class lobbyCliente extends javax.swing.JPanel {
    Cliente cliente = new Cliente();
    /**
     * Creates new form lobbyCliente
     * @param cliente
     */
    public lobbyCliente(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contentLobbyCliente = new javax.swing.JPanel();
        contentMenu = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        contentBoton1C = new javax.swing.JPanel();
        botonVerVehiculos = new javax.swing.JButton();
        contentBoton2C = new javax.swing.JPanel();
        botonBuscarVehiculos = new javax.swing.JButton();
        contentBoton3C = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JButton();
        contentOpciones = new javax.swing.JPanel();

        contentLobbyCliente.setBackground(new java.awt.Color(255, 255, 255));

        contentMenu.setBackground(new java.awt.Color(25, 69, 113));

        labelMenu.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(192, 192, 192));
        labelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu.setText("MENÚ");

        contentBoton1C.setBackground(new java.awt.Color(51, 153, 255));

        botonVerVehiculos.setBackground(new java.awt.Color(0, 51, 102));
        botonVerVehiculos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        botonVerVehiculos.setForeground(new java.awt.Color(192, 192, 192));
        botonVerVehiculos.setText("VER VEHICULOS");
        botonVerVehiculos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonVerVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerVehiculos.setFocusPainted(false);
        botonVerVehiculos.setFocusable(false);
        botonVerVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentBoton1CLayout = new javax.swing.GroupLayout(contentBoton1C);
        contentBoton1C.setLayout(contentBoton1CLayout);
        contentBoton1CLayout.setHorizontalGroup(
            contentBoton1CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVerVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentBoton1CLayout.setVerticalGroup(
            contentBoton1CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVerVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        contentBoton2C.setBackground(new java.awt.Color(102, 204, 255));

        botonBuscarVehiculos.setBackground(new java.awt.Color(0, 51, 102));
        botonBuscarVehiculos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        botonBuscarVehiculos.setForeground(new java.awt.Color(192, 192, 192));
        botonBuscarVehiculos.setText("BUSCAR VEHICULOS");
        botonBuscarVehiculos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonBuscarVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarVehiculos.setFocusPainted(false);
        botonBuscarVehiculos.setFocusable(false);
        botonBuscarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentBoton2CLayout = new javax.swing.GroupLayout(contentBoton2C);
        contentBoton2C.setLayout(contentBoton2CLayout);
        contentBoton2CLayout.setHorizontalGroup(
            contentBoton2CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonBuscarVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentBoton2CLayout.setVerticalGroup(
            contentBoton2CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonBuscarVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        contentBoton3C.setBackground(new java.awt.Color(25, 69, 113));

        javax.swing.GroupLayout contentBoton3CLayout = new javax.swing.GroupLayout(contentBoton3C);
        contentBoton3C.setLayout(contentBoton3CLayout);
        contentBoton3CLayout.setHorizontalGroup(
            contentBoton3CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        contentBoton3CLayout.setVerticalGroup(
            contentBoton3CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botonCerrar.setBackground(new java.awt.Color(192, 192, 192));
        botonCerrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(0, 51, 102));
        botonCerrar.setText("CERRAR SESION");
        botonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.setFocusPainted(false);
        botonCerrar.setFocusable(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentMenuLayout = new javax.swing.GroupLayout(contentMenu);
        contentMenu.setLayout(contentMenuLayout);
        contentMenuLayout.setHorizontalGroup(
            contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentBoton1C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentBoton2C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentBoton3C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(contentMenuLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentMenuLayout.setVerticalGroup(
            contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelMenu)
                .addGap(18, 18, 18)
                .addComponent(contentBoton1C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentBoton2C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentBoton3C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        contentOpciones.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout contentOpcionesLayout = new javax.swing.GroupLayout(contentOpciones);
        contentOpciones.setLayout(contentOpcionesLayout);
        contentOpcionesLayout.setHorizontalGroup(
            contentOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        contentOpcionesLayout.setVerticalGroup(
            contentOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLobbyClienteLayout = new javax.swing.GroupLayout(contentLobbyCliente);
        contentLobbyCliente.setLayout(contentLobbyClienteLayout);
        contentLobbyClienteLayout.setHorizontalGroup(
            contentLobbyClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLobbyClienteLayout.createSequentialGroup()
                .addComponent(contentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentLobbyClienteLayout.setVerticalGroup(
            contentLobbyClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLobbyClienteLayout.createSequentialGroup()
                .addComponent(contentOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(contentMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentLobbyCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentLobbyCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerVehiculosActionPerformed
        verVehiculoCliente ventana = new verVehiculoCliente(cliente);
        ventana.setSize(560, 500);
        ventana.setLocation(0,0);
        contentOpciones.removeAll();
        contentOpciones.add(ventana);
        contentOpciones.revalidate();
        contentOpciones.repaint();
    }//GEN-LAST:event_botonVerVehiculosActionPerformed

    private void botonBuscarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarVehiculosActionPerformed
        buscarVehiculoCliente ventana = new buscarVehiculoCliente(cliente);
        ventana.setSize(540, 500);
        ventana.setLocation(0,0);
        contentOpciones.removeAll();
        contentOpciones.add(ventana);
        contentOpciones.revalidate();
        contentOpciones.repaint();
    }//GEN-LAST:event_botonBuscarVehiculosActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        inicio ventana = new inicio();
        ventana.setSize(800,500);
        ventana.setLocation(0, 0);
        contentLobbyCliente.removeAll();
        contentLobbyCliente.add(ventana);
        contentLobbyCliente.revalidate();
        contentLobbyCliente.repaint();
        
    }//GEN-LAST:event_botonCerrarActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarVehiculos;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonVerVehiculos;
    private javax.swing.JPanel contentBoton1C;
    private javax.swing.JPanel contentBoton2C;
    private javax.swing.JPanel contentBoton3C;
    private javax.swing.JPanel contentLobbyCliente;
    private javax.swing.JPanel contentMenu;
    private javax.swing.JPanel contentOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMenu;
    // End of variables declaration//GEN-END:variables
}
