/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author PROGRAMAR
 */
public class lobbyGerente extends javax.swing.JPanel {

    /**
     * Creates new form lobbyGerente
     */
    public lobbyGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contentLobbyGerente = new javax.swing.JPanel();
        contentMenu = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        contentBoton2C = new javax.swing.JPanel();
        botonVendedor2 = new javax.swing.JButton();
        contentBoton3C = new javax.swing.JPanel();
        botonVendedor3 = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        botonVendedor4 = new javax.swing.JButton();
        contentOpciones = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        contentLobbyGerente.setBackground(new java.awt.Color(255, 255, 255));
        contentLobbyGerente.setPreferredSize(new java.awt.Dimension(800, 500));

        contentMenu.setBackground(new java.awt.Color(25, 69, 113));

        labelMenu.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(192, 192, 192));
        labelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenu.setText("MENÚ");

        contentBoton2C.setBackground(new java.awt.Color(0, 51, 102));

        botonVendedor2.setBackground(new java.awt.Color(0, 51, 102));
        botonVendedor2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        botonVendedor2.setForeground(new java.awt.Color(192, 192, 192));
        botonVendedor2.setText("VER VENDEDORES");
        botonVendedor2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonVendedor2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVendedor2.setFocusPainted(false);
        botonVendedor2.setFocusable(false);
        botonVendedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVendedor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentBoton2CLayout = new javax.swing.GroupLayout(contentBoton2C);
        contentBoton2C.setLayout(contentBoton2CLayout);
        contentBoton2CLayout.setHorizontalGroup(
            contentBoton2CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVendedor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentBoton2CLayout.setVerticalGroup(
            contentBoton2CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVendedor2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        contentBoton3C.setBackground(new java.awt.Color(0, 51, 102));

        botonVendedor3.setBackground(new java.awt.Color(0, 51, 102));
        botonVendedor3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        botonVendedor3.setForeground(new java.awt.Color(192, 192, 192));
        botonVendedor3.setText("VER CLIENTES");
        botonVendedor3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonVendedor3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVendedor3.setFocusPainted(false);
        botonVendedor3.setFocusable(false);
        botonVendedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVendedor3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentBoton3CLayout = new javax.swing.GroupLayout(contentBoton3C);
        contentBoton3C.setLayout(contentBoton3CLayout);
        contentBoton3CLayout.setHorizontalGroup(
            contentBoton3CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVendedor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentBoton3CLayout.setVerticalGroup(
            contentBoton3CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonVendedor3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        botonCerrar.setBackground(new java.awt.Color(192, 192, 192));
        botonCerrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(0, 51, 102));
        botonCerrar.setText("CERRAR SESION");
        botonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.setFocusPainted(false);
        botonCerrar.setFocusable(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonVendedor4.setBackground(new java.awt.Color(0, 51, 102));
        botonVendedor4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        botonVendedor4.setForeground(new java.awt.Color(192, 192, 192));
        botonVendedor4.setText("AGREGAR VENDEDOR");
        botonVendedor4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonVendedor4.setPreferredSize(new java.awt.Dimension(148, 50));
        botonVendedor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVendedor4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentMenuLayout = new javax.swing.GroupLayout(contentMenu);
        contentMenu.setLayout(contentMenuLayout);
        contentMenuLayout.setHorizontalGroup(
            contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentBoton2C, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentBoton3C, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVendedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(contentMenuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentMenuLayout.setVerticalGroup(
            contentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelMenu)
                .addGap(35, 35, 35)
                .addComponent(contentBoton2C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentBoton3C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVendedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        contentOpciones.setBackground(new java.awt.Color(0, 51, 102));
        contentOpciones.setAlignmentX(0.0F);
        contentOpciones.setAlignmentY(0.0F);

        javax.swing.GroupLayout contentOpcionesLayout = new javax.swing.GroupLayout(contentOpciones);
        contentOpciones.setLayout(contentOpcionesLayout);
        contentOpcionesLayout.setHorizontalGroup(
            contentOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        contentOpcionesLayout.setVerticalGroup(
            contentOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLobbyGerenteLayout = new javax.swing.GroupLayout(contentLobbyGerente);
        contentLobbyGerente.setLayout(contentLobbyGerenteLayout);
        contentLobbyGerenteLayout.setHorizontalGroup(
            contentLobbyGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLobbyGerenteLayout.createSequentialGroup()
                .addComponent(contentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLobbyGerenteLayout.setVerticalGroup(
            contentLobbyGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentLobbyGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentLobbyGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVendedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVendedor2ActionPerformed
        verEmpleados ventana = new verEmpleados();
        ventana.setSize(560,500);
        ventana.setLocation(0,0);
        contentOpciones.removeAll();
        contentOpciones.add(ventana);
        contentOpciones.revalidate();
        contentOpciones.repaint();
    }//GEN-LAST:event_botonVendedor2ActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        inicio ventana = new inicio();
        ventana.setSize(800,500);
        ventana.setLocation(0, 0);
        contentLobbyGerente.removeAll();
        contentLobbyGerente.add(ventana);
        contentLobbyGerente.revalidate();
        contentLobbyGerente.repaint();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonVendedor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVendedor3ActionPerformed
        verClientes ventana = new verClientes();
        ventana.setSize(560,500);
        ventana.setLocation(0, 0);
        contentOpciones.removeAll();
        contentOpciones.add(ventana);
        contentOpciones.revalidate();
        contentOpciones.repaint();
    }//GEN-LAST:event_botonVendedor3ActionPerformed

    private void botonVendedor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVendedor4ActionPerformed
        agregarVendedor ventana = new agregarVendedor();
        ventana.setSize(560, 500);
        ventana.setLocation(0,0);
        contentOpciones.removeAll();
        contentOpciones.add(ventana);
        contentOpciones.revalidate();
        contentOpciones.repaint();

    }//GEN-LAST:event_botonVendedor4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonVendedor2;
    private javax.swing.JButton botonVendedor3;
    private javax.swing.JButton botonVendedor4;
    private javax.swing.JPanel contentBoton2C;
    private javax.swing.JPanel contentBoton3C;
    private javax.swing.JPanel contentLobbyGerente;
    private javax.swing.JPanel contentMenu;
    private javax.swing.JPanel contentOpciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMenu;
    // End of variables declaration//GEN-END:variables
}
