/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.Auto;
import logica.Camioneta;
import logica.Moto;
import logica.Vehiculo;
import logica.Vendedor;

/**
 *
 * @author guada
 */
public class ModificarVehiculo extends javax.swing.JFrame {
    /**
     * Creates new form ModificarVehiculo
     */
    Vendedor vendedor = new Vendedor();
    Vehiculo vehiculo;
    FuncionRepetida func = new FuncionRepetida();
    
    public ModificarVehiculo(int id, verVehiculoVendedor aThis) throws SQLException {
        initComponents();
        labelPuertas.setVisible(false);
        labelEmb.setVisible(false);
        labelTracc.setVisible(false);
        labelPas.setVisible(false);
        intPuertas.setVisible(false);
        txtTraccion.setVisible(false);
        intPasajeros.setVisible(false);
        txtEmbrague.setVisible(false);

        cargarVehiculo(id);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
            aThis.mostrar("Vehiculos"); 
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        intPotencia = new javax.swing.JFormattedTextField();
        txtColor = new javax.swing.JFormattedTextField();
        intKm = new javax.swing.JFormattedTextField();
        txtCond = new javax.swing.JFormattedTextField();
        txtMarca = new javax.swing.JFormattedTextField();
        txtModelo = new javax.swing.JFormattedTextField();
        intPrecio = new javax.swing.JFormattedTextField();
        labelPuertas = new javax.swing.JLabel();
        labelTracc = new javax.swing.JLabel();
        labelEmb = new javax.swing.JLabel();
        labelPas = new javax.swing.JLabel();
        intPuertas = new javax.swing.JFormattedTextField();
        txtTraccion = new javax.swing.JFormattedTextField();
        intPasajeros = new javax.swing.JFormattedTextField();
        txtEmbrague = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(25, 69, 113));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 192, 192));
        jLabel1.setText("Marca");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(192, 192, 192));
        jLabel2.setText("Modelo");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(192, 192, 192));
        jLabel3.setText("Color");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(192, 192, 192));
        jLabel4.setText("Kilometros");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(192, 192, 192));
        jLabel5.setText("Condición");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(192, 192, 192));
        jLabel6.setText("Potencia");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(192, 192, 192));
        jLabel8.setText("Precio");

        btnModificar.setBackground(new java.awt.Color(192, 192, 192));
        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 51, 102));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.setFocusPainted(false);
        btnModificar.setFocusable(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        intPotencia.setBackground(new java.awt.Color(192, 192, 192));
        intPotencia.setForeground(new java.awt.Color(0, 51, 102));
        intPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intPotenciaActionPerformed(evt);
            }
        });

        txtColor.setBackground(new java.awt.Color(192, 192, 192));
        txtColor.setForeground(new java.awt.Color(0, 51, 102));

        intKm.setBackground(new java.awt.Color(192, 192, 192));
        intKm.setForeground(new java.awt.Color(0, 51, 102));
        intKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intKmActionPerformed(evt);
            }
        });

        txtCond.setBackground(new java.awt.Color(192, 192, 192));
        txtCond.setForeground(new java.awt.Color(0, 51, 102));

        txtMarca.setBackground(new java.awt.Color(192, 192, 192));
        txtMarca.setForeground(new java.awt.Color(0, 51, 102));

        txtModelo.setBackground(new java.awt.Color(192, 192, 192));
        txtModelo.setForeground(new java.awt.Color(0, 51, 102));

        intPrecio.setBackground(new java.awt.Color(192, 192, 192));
        intPrecio.setForeground(new java.awt.Color(0, 51, 102));

        labelPuertas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        labelPuertas.setForeground(new java.awt.Color(192, 192, 192));
        labelPuertas.setText("Cantidad de puertas");

        labelTracc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        labelTracc.setForeground(new java.awt.Color(192, 192, 192));
        labelTracc.setText("Tipo de tracción");

        labelEmb.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        labelEmb.setForeground(new java.awt.Color(192, 192, 192));
        labelEmb.setText("Tipo de Embrague");

        labelPas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        labelPas.setForeground(new java.awt.Color(192, 192, 192));
        labelPas.setText("Cantidad de Pasajeros");

        intPuertas.setBackground(new java.awt.Color(192, 192, 192));
        intPuertas.setForeground(new java.awt.Color(0, 51, 102));

        txtTraccion.setBackground(new java.awt.Color(192, 192, 192));
        txtTraccion.setForeground(new java.awt.Color(0, 51, 102));

        intPasajeros.setBackground(new java.awt.Color(192, 192, 192));
        intPasajeros.setForeground(new java.awt.Color(0, 51, 102));
        intPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intPasajerosActionPerformed(evt);
            }
        });

        txtEmbrague.setBackground(new java.awt.Color(192, 192, 192));
        txtEmbrague.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(labelPuertas)
                    .addComponent(labelTracc)
                    .addComponent(labelEmb)
                    .addComponent(labelPas))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtCond, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtColor, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtTraccion, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtEmbrague, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(intPuertas)
                    .addComponent(intPrecio)
                    .addComponent(intKm)
                    .addComponent(intPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(intPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(intKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(intPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(intPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelPuertas)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTracc)
                            .addComponent(txtTraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(intPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmb)
                    .addComponent(txtEmbrague, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPas)
                    .addComponent(intPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        String color = txtColor.getText();
        int km = Integer.parseInt(String.valueOf(intKm.getText()));
        String cond = txtCond.getText();
        double pot = Double.parseDouble(String.valueOf(intPotencia.getText()));
        double precio = Double.parseDouble(String.valueOf(intPrecio.getText()));
        
       
        if (intPuertas.isVisible()) {
            try {
                int cantPuertas = Integer.parseInt(String.valueOf(intPuertas.getText()));
                if(km < 0 || pot < 0 || precio < 0 || cantPuertas <= 0) {
                    throw new IllegalArgumentException();
                }
                Auto auto = (Auto) vehiculo;
                vendedor.modificarVehiculo(auto, marca, modelo, color, km, cond, pot, precio, cantPuertas, null, null, 0);
            } catch (SQLException ex) {
                Logger.getLogger(ModificarVehiculo.class.getName()).log(Level.SEVERE, null, ex); 
            } catch(IllegalArgumentException e){
                e.getMessage();
                func.mostrarMensaje("Valores menores a cero", "Error", "VEHICULO NO PUBLICADO");
            }
        } else if (txtTraccion.isVisible()) {
            try {
                String traccion = txtTraccion.getText();
                if(km < 0 || pot < 0 || precio < 0 || precio <= 0) {
                    throw new IllegalArgumentException();
                }
                Camioneta camioneta = (Camioneta) vehiculo;
                vendedor.modificarVehiculo(camioneta, marca, modelo, color, km, cond, pot, precio, 0 ,traccion, null, 0);
            } catch (SQLException ex) {
                Logger.getLogger(ModificarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
            } catch(IllegalArgumentException e){
                e.getMessage();
                func.mostrarMensaje("Valores menores a cero", "Error", "VEHICULO NO PUBLICADO");
            }
        } else {
            try {
                String embrague = txtEmbrague.getText();
                int cantPasajeros = Integer.parseInt(String.valueOf(intPasajeros.getText()));
                if(km < 0 || pot < 0 || precio < 0 || cantPasajeros < 0) {
                throw new IllegalArgumentException();
                }
                Moto moto = (Moto) vehiculo;
                vendedor.modificarVehiculo(moto, marca, modelo, color, km, cond, pot, precio, 0, null, embrague, cantPasajeros);
            } catch (SQLException ex) {
                Logger.getLogger(ModificarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
            } catch(IllegalArgumentException e){
                e.getMessage();
                func.mostrarMensaje("Valores menores a cero", "Error", "VEHICULO NO PUBLICADO");
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void intKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intKmActionPerformed

    private void intPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intPotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intPotenciaActionPerformed

    private void intPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intPasajerosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JFormattedTextField intKm;
    private javax.swing.JFormattedTextField intPasajeros;
    private javax.swing.JFormattedTextField intPotencia;
    private javax.swing.JFormattedTextField intPrecio;
    private javax.swing.JFormattedTextField intPuertas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelEmb;
    private javax.swing.JLabel labelPas;
    private javax.swing.JLabel labelPuertas;
    private javax.swing.JLabel labelTracc;
    private javax.swing.JFormattedTextField txtColor;
    private javax.swing.JFormattedTextField txtCond;
    private javax.swing.JFormattedTextField txtEmbrague;
    private javax.swing.JFormattedTextField txtMarca;
    private javax.swing.JFormattedTextField txtModelo;
    private javax.swing.JFormattedTextField txtTraccion;
    // End of variables declaration//GEN-END:variables

    private void cargarVehiculo(int id) throws SQLException {
        vehiculo = vendedor.traerVehiculo(id);
        vehiculo.setIdVehiculo(id);
        txtMarca.setText(vehiculo.getMarca());
        txtModelo.setText(vehiculo.getModelo());
        txtColor.setText(vehiculo.getColor());
        intKm.setText(String.valueOf(vehiculo.getKms()));
        txtCond.setText(vehiculo.getCondicion());
        intPotencia.setText(String.valueOf(vehiculo.getPotencia()));
        intPrecio.setText(String.valueOf(vehiculo.getPrecio()));

        if (vehiculo instanceof Auto auto) {
            labelPuertas.setVisible(true);
            intPuertas.setVisible(true);
            intPuertas.setText(String.valueOf(auto.getCantPuertas()));
        } else if (vehiculo instanceof Camioneta camioneta) {
            labelTracc.setVisible(true);  
            txtTraccion.setVisible(true);
            txtTraccion.setText(camioneta.getTipoTaccion());
        } else if(vehiculo instanceof Moto moto) {
            labelEmb.setVisible(true); 
            txtEmbrague.setVisible(true);
            txtEmbrague.setText(moto.getTipoEmbrague());
            labelPas.setVisible(true);
            intPasajeros.setVisible(true);
            intPasajeros.setText(String.valueOf(moto.getCantPasajeros()));  
        }
    }

}
