/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import logica.Vendedor;

/**
 *
 * @author PROGRAMAR
 */
public class publicarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form publicarVehiculo
     */
    Vendedor vendedor = new Vendedor();
    public publicarVehiculo(Vendedor vendedor) {
        initComponents();
        this.vendedor = vendedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentAgregar = new javax.swing.JPanel();
        botonAgregarAuto = new javax.swing.JButton();
        botonAgregarCamioneta = new javax.swing.JButton();
        botonAgregarMoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));
        setPreferredSize(new java.awt.Dimension(560, 500));

        contentAgregar.setBackground(new java.awt.Color(0, 51, 102));
        contentAgregar.setPreferredSize(new java.awt.Dimension(560, 500));

        botonAgregarAuto.setBackground(new java.awt.Color(25, 69, 113));
        botonAgregarAuto.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        botonAgregarAuto.setForeground(new java.awt.Color(192, 192, 192));
        botonAgregarAuto.setText("AUTO");
        botonAgregarAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonAgregarAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarAuto.setFocusPainted(false);
        botonAgregarAuto.setFocusable(false);
        botonAgregarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAutoActionPerformed(evt);
            }
        });

        botonAgregarCamioneta.setBackground(new java.awt.Color(25, 69, 113));
        botonAgregarCamioneta.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        botonAgregarCamioneta.setForeground(new java.awt.Color(192, 192, 192));
        botonAgregarCamioneta.setText("CAMIONETA");
        botonAgregarCamioneta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonAgregarCamioneta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarCamioneta.setFocusPainted(false);
        botonAgregarCamioneta.setFocusable(false);
        botonAgregarCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCamionetaActionPerformed(evt);
            }
        });

        botonAgregarMoto.setBackground(new java.awt.Color(25, 69, 113));
        botonAgregarMoto.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        botonAgregarMoto.setForeground(new java.awt.Color(192, 192, 192));
        botonAgregarMoto.setText("MOTO");
        botonAgregarMoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.darkGray));
        botonAgregarMoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarMoto.setFocusPainted(false);
        botonAgregarMoto.setFocusable(false);
        botonAgregarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarMotoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 192, 192));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIPO DE VEHÍCULO");

        javax.swing.GroupLayout contentAgregarLayout = new javax.swing.GroupLayout(contentAgregar);
        contentAgregar.setLayout(contentAgregarLayout);
        contentAgregarLayout.setHorizontalGroup(
            contentAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAgregarMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgregarAuto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgregarCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentAgregarLayout.setVerticalGroup(
            contentAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentAgregarLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonAgregarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAgregarCamioneta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAgregarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarMotoActionPerformed
       agregarMoto ventana = new agregarMoto(vendedor);
       ventana.setSize(560,520);
       ventana.setVisible(true);
    }//GEN-LAST:event_botonAgregarMotoActionPerformed

    private void botonAgregarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAutoActionPerformed
       agregarAuto ventana = new agregarAuto(vendedor);
       ventana.setSize(560,520);
       ventana.setVisible(true);
    }//GEN-LAST:event_botonAgregarAutoActionPerformed

    private void botonAgregarCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCamionetaActionPerformed
       agregarCamioneta ventana = new agregarCamioneta(vendedor);
       ventana.setSize(560,520);
       ventana.setVisible(true);
    }//GEN-LAST:event_botonAgregarCamionetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarAuto;
    private javax.swing.JButton botonAgregarCamioneta;
    private javax.swing.JButton botonAgregarMoto;
    private javax.swing.JPanel contentAgregar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
