/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Cliente;
import logica.Gerente;
import logica.Vendedor;

/**
 *
 * @author Facultad
 */
public class verClientes extends javax.swing.JPanel {
    Cliente cliente = new Cliente();
    Vendedor vendedor = new Vendedor();
    Gerente gerente = new Gerente();
    FuncionRepetida fun = new FuncionRepetida();
    /**
     * Creates new form verClientes
     */
    public verClientes() {
        initComponents();
        mostrar("Clientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVender = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        verDetalle = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        contentVerClientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        visor1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        btnVendAs = new javax.swing.JButton();

        btnVender.setText("Vender");

        btnVerDetalle.setText("Ver en detalle");

        visor.setBackground(new java.awt.Color(226, 229, 243));
        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Kilometros", "Condicion", "Tipo", "Precio"
            }
        ));
        jScrollPane2.setViewportView(visor);

        verDetalle.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        verDetalle.setForeground(new java.awt.Color(255, 255, 255));
        verDetalle.setText("VER");
        verDetalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 245, 255), new java.awt.Color(238, 245, 255), null, null));
        verDetalle.setContentAreaFilled(false);
        verDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verDetalle.setFocusPainted(false);
        verDetalle.setFocusable(false);

        btnModificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 245, 255), new java.awt.Color(238, 245, 255), null, null));
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setFocusPainted(false);
        btnModificar.setFocusable(false);

        btnEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 245, 255), new java.awt.Color(238, 245, 255), null, null));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setFocusable(false);

        setPreferredSize(new java.awt.Dimension(560, 500));

        contentVerClientes.setBackground(new java.awt.Color(0, 51, 102));

        visor1.setBackground(new java.awt.Color(192, 192, 192));
        visor1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        visor1.setForeground(new java.awt.Color(0, 51, 102));
        visor1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(visor1);

        jButton1.setBackground(new java.awt.Color(192, 192, 192));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("EDITAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(192, 192, 192));
        botonEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 51, 102));
        botonEliminar.setText("ELIMINAR");
        botonEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        btnVendAs.setBackground(new java.awt.Color(192, 192, 192));
        btnVendAs.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnVendAs.setForeground(new java.awt.Color(0, 51, 102));
        btnVendAs.setText("VER VENDEDORES");
        btnVendAs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVendAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendAsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentVerClientesLayout = new javax.swing.GroupLayout(contentVerClientes);
        contentVerClientes.setLayout(contentVerClientesLayout);
        contentVerClientesLayout.setHorizontalGroup(
            contentVerClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentVerClientesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(contentVerClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentVerClientesLayout.createSequentialGroup()
                        .addComponent(btnVendAs, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        contentVerClientesLayout.setVerticalGroup(
            contentVerClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentVerClientesLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentVerClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botonEliminar)
                    .addComponent(btnVendAs))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVerClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentVerClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void mostrar(String tabla) {
        List<String[]> clientes = vendedor.mostrarClientes(tabla, "C");

        DefaultTableModel model = new DefaultTableModel(){

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        visor1.getTableHeader().setResizingAllowed(false);
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Dni");
        model.addColumn("Empresa");
        for (String[] cliente : clientes) {
            model.addRow(cliente);
        }
        visor1.setModel(model);
    }

    private void btnVender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender1ActionPerformed
        if(visor1.getRowCount() > 0) {
            if(visor1.getSelectedRow() != -1) {
                int idCliente = Integer.parseInt(String.valueOf(visor1.getValueAt(visor1.getSelectedRow(), 0)));
                ModificarCliente modifVend = new ModificarCliente(idCliente, this);
                modifVend.setVisible(true);
                modifVend.setLocationRelativeTo(null);
                
            } else {
                fun.mostrarMensaje("No se ha seleccionado ningún cliente para ver en detalle", "Error", "¡ERROR!");
            }
        } else {
            fun.mostrarMensaje("No se encuentran clientes registrados", "Error", "¡ERROR!");
        }
    }//GEN-LAST:event_btnVender1ActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if(visor1.getRowCount() > 0) {
            if(visor1.getSelectedRow() != -1) {
                int idCliente = Integer.parseInt(String.valueOf(visor1.getValueAt(visor1.getSelectedRow(), 0)));
                try {
                    cliente.eliminar(idCliente);
                } catch (SQLException ex) {
                    Logger.getLogger(verClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
                ;
                fun.mostrarMensaje("Cliente eliminado con éxito", "Info", "Felicitaciones");
            } else {
                fun.mostrarMensaje("No se ha seleccionado ningun cliente", "Error", "¡ERROR!");
            }
        } else {
            fun.mostrarMensaje("No se encuentran clientes registrados", "Error", "¡ERROR!");
        }

        mostrar("Clientes");
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(visor1.getRowCount() > 0) {
            if(visor1.getSelectedRow() != -1) {
                int idCliente = Integer.parseInt(String.valueOf(visor1.getValueAt(visor1.getSelectedRow(), 0)));
                ModificarCliente modifVend = new ModificarCliente(idCliente, this);
                modifVend.setVisible(true);
                modifVend.setLocationRelativeTo(null);
                
            } else {
                fun.mostrarMensaje("No se ha seleccionado ningún cliente para ver en detalle", "Error", "¡ERROR!");
            }
        } else {
            fun.mostrarMensaje("No se encuentran clientes registrados", "Error", "¡ERROR!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVendAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendAsActionPerformed
        if(visor1.getRowCount() > 0) {
            if(visor1.getSelectedRow() != -1) {
                int idCliente = Integer.parseInt(String.valueOf(visor1.getValueAt(visor1.getSelectedRow(), 0)));
                VendedoresAsociados venAs = new VendedoresAsociados(idCliente);
                venAs.setVisible(true);
                venAs.setLocationRelativeTo(null);
            } else {
                fun.mostrarMensaje("No se ha seleccionado ningún cliente para ver en detalle", "Error", "¡ERROR!");
            }
        } else {
            fun.mostrarMensaje("No se encuentran clientes registrados", "Error", "¡ERROR!");
        }
    }//GEN-LAST:event_btnVendAsActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVendAs;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JPanel contentVerClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton verDetalle;
    public javax.swing.JTable visor;
    private javax.swing.JTable visor1;
    // End of variables declaration//GEN-END:variables
}
