/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import logica.Vendedor;

/**
 *
 * @author PROGRAMAR
 */
public class verVehiculoVendedor extends javax.swing.JPanel {
    Vendedor vendedor = new Vendedor();
    FuncionRepetida fun = new FuncionRepetida();
    /**
     * Creates new form verVehiculoCliente
     */
    public verVehiculoVendedor() {
        initComponents();
        mostrar("Vehiculos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contentPrincipalVer = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();

        contentPrincipalVer.setBackground(new java.awt.Color(0, 51, 102));

        btnModificar.setBackground(new java.awt.Color(192, 192, 192));
        btnModificar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 51, 102));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 245, 255), new java.awt.Color(238, 245, 255), null, null));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(192, 192, 192));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 51, 102));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(238, 245, 255), new java.awt.Color(238, 245, 255), null, null));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        visor.setBackground(new java.awt.Color(192, 192, 192));
        visor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        visor.setForeground(new java.awt.Color(0, 51, 102));
        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Kilometros", "Condicion", "Tipo", "Precio"
            }
        ));
        visor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(visor);

        javax.swing.GroupLayout contentPrincipalVerLayout = new javax.swing.GroupLayout(contentPrincipalVer);
        contentPrincipalVer.setLayout(contentPrincipalVerLayout);
        contentPrincipalVerLayout.setHorizontalGroup(
            contentPrincipalVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPrincipalVerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(contentPrincipalVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPrincipalVerLayout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        contentPrincipalVerLayout.setVerticalGroup(
            contentPrincipalVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPrincipalVerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentPrincipalVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPrincipalVer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPrincipalVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void mostrar(String tabla) {
        List<String[]> vehiculos = vendedor.mostrarInventario(tabla);

        DefaultTableModel model = new DefaultTableModel(){

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        visor.getTableHeader().setResizingAllowed(false);
        model.addColumn("ID");
        model.addColumn("Marca");
        model.addColumn("Modelo");
        model.addColumn("Kilometros");
        model.addColumn("Condición");
        model.addColumn("Tipo");
        model.addColumn("Precio");

        for (String[] vehiculo : vehiculos) {
            model.addRow(vehiculo);
        }
        visor.setModel(model);
    }
    
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(visor.getRowCount() > 0) {
            if(visor.getSelectedRow() != -1) {
                int idVehiculo = Integer.parseInt(String.valueOf(visor.getValueAt(visor.getSelectedRow(), 0)));
                ModificarVehiculo modif;
                try {
                    modif = new ModificarVehiculo(idVehiculo, this);
                    modif.setVisible(true);
                    modif.setLocationRelativeTo(null);
                } catch (SQLException ex) {
                    Logger.getLogger(verVehiculoVendedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                fun.mostrarMensaje("No se ha seleccionado ningún vehículo para modificar", "Error", "¡ERROR!");
            }
        } else {
            fun.mostrarMensaje("No se encuentran vehículos registrados", "Error", "¡ERROR!");
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(visor.getRowCount() > 0) {
            if(visor.getSelectedRow() != -1) {
                try {
                    int idVehiculo = Integer.parseInt(String.valueOf(visor.getValueAt(visor.getSelectedRow(), 0)));
                    vendedor.eliminarVehiculo(idVehiculo);
                    fun.mostrarMensaje("Vehículo eliminado con éxito", "Info", "Borrado exitoso");
                } catch (SQLException ex) {
                    Logger.getLogger(verVehiculoVendedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                fun.mostrarMensaje("No se ha seleccionado ningún vehículo para eliminar", "Error", "¡ERROR!");
            }
        } else {
            fun.mostrarMensaje("No se encuentran vehículos registrados", "Error", "¡ERROR!");
        }

        mostrar("Vehiculos");
    }//GEN-LAST:event_btnEliminarActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel contentPrincipalVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
