
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var g=a[e];g in c||(c[g]={});c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,e){$jscomp.initSymbolIterator();c=null!=c?c:function(a){return a};var b=[],f=a[Symbol.iterator];if("function"==typeof f)for(a=f.call(a);!(f=a.next()).done;)b.push(c.call(e,f.value));else{f=a.length;for(var d=0;d<f;d++)b.push(c.call(e,a[d]))}return b}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";for(var g=b.length,f=a.length,d=Math.max(0,Math.min(c|0,b.length)),h=0;h<f&&d<g;)if(b[d++]!=a[h++])return!1;return h>=f}},"es6","es3");function outerFind(a,b){var c=Array.from(a.querySelectorAll(b));a.matches(b)&&c.splice(0,0,a);return c}
function updateId(a){0!==a.querySelectorAll(".nav-tabs").length&&outerFind(a,'section[id^="tabs"], section.tabs, section[id^="extTabs"], section [class*="-tabs"]').forEach(function(b){if("SECTION"===b.tagName){var c=b.getAttribute("id"),e=b.querySelectorAll(".nav-tabs > .nav-item");b.querySelectorAll(".tab-pane").forEach(function(a,b){a.setAttribute("id",c+"_tab"+b);0===b?(a.classList.contains("active")||a.classList.add("active"),a.classList.contains("show")||a.classList.add("show")):(a.classList.remove("active"),
a.classList.remove("show"))});e.forEach(function(b,e){var d=b.querySelector("a");d.setAttribute("href","#"+c+"_tab"+e);a.getAttribute("data-bs-version")&&a.getAttribute("data-bs-version").startsWith("5")&&d.setAttribute("data-bs-toggle","tab");0===e?(d.classList.contains("active")||d.classList.add("active"),d.classList.contains("show")||d.classList.add("show")):(d.classList.remove("active"),d.classList.remove("show"),d.removeAttribute("active"))})}})}var $,isJQuery="function"==typeof jQuery;
isJQuery&&($=jQuery);var isBuilder=document.querySelector("html").classList.contains("is-builder");if(isBuilder&&isJQuery)$(document).on("add.cards",function(a){updateId(a.target)});else"undefined"===typeof window.initTabsPlugin&&(window.initTabsPlugin=!0,updateId(document.body));
