
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,k){b!=Array.prototype&&b!=Object.prototype&&(b[d]=k.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var d=0;return $jscomp.iteratorPrototype(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.polyfill=function(b,d,k,p){if(d){k=$jscomp.global;b=b.split(".");for(p=0;p<b.length-1;p++){var m=b[p];m in k||(k[m]={});k=k[m]}b=b[b.length-1];p=k[b];d=d(p);d!=p&&null!=d&&$jscomp.defineProperty(k,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.from",function(b){return b?b:function(b,k,p){$jscomp.initSymbolIterator();k=null!=k?k:function(b){return b};var d=[],l=b[Symbol.iterator];if("function"==typeof l)for(b=l.call(b);!(l=b.next()).done;)d.push(k.call(p,l.value));else{l=b.length;for(var w=0;w<l;w++)d.push(k.call(p,b[w]))}return d}},"es6","es3");$jscomp.owns=function(b,d){return Object.prototype.hasOwnProperty.call(b,d)};
$jscomp.polyfill("Object.values",function(b){return b?b:function(b){var d=[],p;for(p in b)$jscomp.owns(b,p)&&d.push(b[p]);return d}},"es8","es3");$jscomp.findInternal=function(b,d,k){b instanceof String&&(b=String(b));for(var p=b.length,m=0;m<p;m++){var l=b[m];if(d.call(k,l,m,b))return{i:m,v:l}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,k){return $jscomp.findInternal(this,b,k).v}},"es6","es3");
$jscomp.checkStringArgs=function(b,d,k){if(null==b)throw new TypeError("The 'this' value for String.prototype."+k+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+k+" must not be a regular expression");return b+""};
$jscomp.polyfill("String.prototype.startsWith",function(b){return b?b:function(b,k){var d=$jscomp.checkStringArgs(this,b,"startsWith");b+="";for(var m=d.length,l=b.length,w=Math.max(0,Math.min(k|0,d.length)),t=0;t<l&&w<m;)if(d[w++]!=b[t++])return!1;return t>=l}},"es6","es3");$jscomp.polyfill("Object.is",function(b){return b?b:function(b,k){return b===k?0!==b||1/b===1/k:b!==b&&k!==k}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(b,k){var d=this;d instanceof String&&(d=String(d));for(var m=d.length,l=k||0;l<m;l++)if(d[l]==b||Object.is(d[l],b))return!0;return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(b,k){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,k||0)}},"es6","es3");
(function(){function b(a,c){var f=Array.from(a.querySelectorAll(c));a.matches&&a.matches(c)&&f.splice(0,0,a);return f}function d(a){a=a.getBoundingClientRect();var c=document.documentElement;return{top:a.top+window.pageYOffset-c.clientTop,left:a.left+window.pageXOffset-c.clientLeft}}function k(a){return parseFloat(getComputedStyle(a,null).height.replace("px",""))}function p(a){return parseFloat(getComputedStyle(a,null).width.replace("px",""))}function m(a){"loading"!=document.readyState?a():document.addEventListener("DOMContentLoaded",
a)}function l(a){(function f(){0>(a.style.opacity-=.1)?a.style.display="none":requestAnimationFrame(f)})()}function w(a){a.style.display="block";(function f(){var e=parseFloat(a.style.opacity);1<(e+=.1)||(a.style.opacity=e,requestAnimationFrame(f))})()}function t(a){var c=[],f={blackberry:"BlackBerry",android:"Android",windows:"IEMobile",opera:"Opera Mini",ios:"iPhone|iPad|iPod"};a="undefined"==typeof a?"*":a.toLowerCase();"*"===a?c=Object.values(f):a in f&&c.push(f[a]);return!(!c.length||!navigator.userAgent.match(new RegExp(c.join("|"),
"i")))}function B(a){var c=a.querySelector(".carousel-item");a=a.querySelector(".carousel-indicators > li");c.classList.add("active");a&&a.classList.add("active")}function y(a){var c=a.getAttribute("id")+"-carousel",f=a.getAttribute("data-bs-version")&&a.getAttribute("data-bs-version").startsWith("5");null===a.getAttribute("id")&&(c=a.classList.value.match(/cid-.*?(?=\s|$)/)+"-carousel");a.querySelectorAll(".carousel").forEach(function(a){a.setAttribute("id",c)});a.querySelector(".carousel-controls")&&
a.querySelectorAll(".carousel-controls").forEach(function(a){a.querySelectorAll("a").forEach(function(a){a.setAttribute("href","#"+c);f?a.setAttribute("data-bs-target","#"+c):a.setAttribute("data-target","#"+c)})});a.querySelectorAll(".carousel-indicators > li").forEach(function(a){f?a.setAttribute("data-bs-target","#"+c):a.setAttribute("data-target","#"+c)});B(a)}function G(a){var c=a.querySelectorAll(".carousel-item").length,f=a.querySelector(".carousel-inner").getAttribute("data-visible");c<f&&
(f=c);a.querySelectorAll(".carousel-inner").forEach(function(a){a.setAttribute("class","carousel-inner slides"+f)});a.querySelectorAll(".clonedCol").forEach(function(a){a.remove()});a.querySelectorAll(".carousel-item .col-md-12").forEach(function(a){2>f?a.setAttribute("class","col-md-12"):"5"==f?a.setAttribute("class","col-md-12 col-lg-15"):a.setAttribute("class","col-md-12 col-lg-"+12/f)});a.querySelectorAll(".carousel-item .row").forEach(function(a){a.setAttribute("style","-webkit-flex-grow: 1; flex-grow: 1; margin: 0;")});
a.querySelectorAll(".carousel-item").forEach(function(a){for(var c=a,b=1;b<f;b++){(c=c.nextElementSibling)||(c=a.parentNode.children[0]===a?a.nextElementSibling:a.parentNode.children[0]);var e;if(e=c){var d=0;do d++;while(e=e.previousElementSibling);e=d}else e=-1;d=c.querySelector(".col-md-12").cloneNode(!0);d.classList.add("cloneditem-"+b);d.classList.add("clonedCol");d.setAttribute("data-cloned-index",e);a.children[0].appendChild(d)}})}function H(a){var c="",b=a.querySelector("svg linearGradient");
if(b){c=[];b=Array.from(b.children);for(var e=0;e<b.length;e++)c.push('"'+b[e].getAttribute("stop-color")+'"');c='"lineargradient": ['+c+"],";Array.from(a.querySelectorAll("svg")).some(function(a){return a.classList.contains("svg-gradient")})||a.querySelectorAll("svg").forEach(function(a){a.classList.add("svg-gradient")})}return c}function z(a,c,b){var f=a.closest(".card"),g=f.parentElement.classList;f.getAttribute("style")||f.setAttribute("style","-webkit-flex-basis: auto; flex-basis: auto;");g.contains("row")&&
(g.remove("row"),g.add("media-container-row"));a.querySelectorAll(".svg-gradient > *").forEach(function(a){a.setAttribute("id",c)});f=a.cloneNode(!0);Array.from(a.children).forEach(function(a){if("SVG"!==a.tagName)return a.remove()});a.setAttribute("data-pie","{ "+H(a.closest("section"))+' "percent": '+b+', "size": 150, "colorCircle": "#f1f1f1", "stroke": 5, "colorSlice": "url(#'+c+')", "fontSize": "1.3rem", "number": false }');Array.from(f.children).forEach(function(c){switch(!0){case c.matches("p"):c.innerText=
b+"%";a.appendChild(c);break;case c.matches("svg"):break;default:a.appendChild(c)}})}function C(a){var c=a.closest("section").getAttribute("id")+"-svg-gradient",b=+a.getAttribute("data-goal");z(a,c,b)}function I(a,c){if(a.classList.contains("circle-progress-section")&&c.includes("progress")&&"progressCount"!=c)if(c.includes("Color"))a.querySelectorAll(".pie_progress").forEach(function(c){var b=a.getAttribute("id")+"-svg-gradient",f=+c.getAttribute("data-goal");z(c,b,f)});else{var b=a.getAttribute("id")+
"-svg-gradient",e=a.querySelector("."+c),g=+e.getAttribute("data-goal");z(e,b,g)}}function D(){if(document.querySelector(".loop-container")){var a=function(c){var b=0,e=0,g=+c.children[0].dataset.speed||.05,d=c.querySelector(".item"),h=d.dataset.direction;if(d){(function(){c.querySelectorAll(".item").forEach(function(a){a.textContent=a.dataset.linewords+"\u00a0"})})();c.style.cssText="position: relative; display: inline-flex; white-space: nowrap;";c.children[1].style.cssText="position: absolute; left: "+
100*-h+"%;";var k=function(){e+=g;b=.8*b+.2*e;100<e&&(b-=e,e=0);c.style.transform="translateX("+b*h+"%)";window.requestAnimationFrame(k)},n=new MutationObserver(function(){document.querySelectorAll(".loop-container").forEach(function(a){a.style.transform=""});n.disconnect();a(c)});n.observe(d,{attributes:!0,attributeFilter:["data-direction","data-speed","data-linewords"]});(function(){window.addEventListener("scroll",function(){return e+=1.5*g})})();k()}};document.querySelectorAll(".loop-container").forEach(function(c){return a(c)})}}
function E(){var a=Array.from(document.querySelectorAll(".ticker__item"));if(0!==a.length){var c=a.map(function(a){return a.textContent}),b=new MutationObserver(function(){a.forEach(function(a,c){a.textContent=a.dataset.word})});a.forEach(function(a,f){a.textContent=c[f];b.observe(a,{attributes:!0,attributeFilter:["data-word"]})});(function(){document.querySelectorAll(".ticker__item").forEach(function(a){a.textContent=a.dataset.word})})()}}var h,n,r="function"==typeof jQuery;r&&(h=jQuery);h?n=h("html").hasClass("is-builder"):
n=document.querySelector("html").classList.contains("is-builder");Element.prototype.parents=function(a){for(var c=[],b=this,e=void 0!==a;null!==(b=b.parentElement);)b.nodeType===Node.ELEMENT_NODE&&(e&&!b.matches(a)||c.push(b));return c};Element.prototype.footerReveal=function(){function a(){!e&&b.offsetHeight<=window.outerHeight?(b.style.zIndex="-999",b.style.position="fixed",b.style.bottom="0",b.style.width=f.offsetWidth+"px",f.style.marginBottom=b.offsetHeight+"px"):(b.style.zIndex="",b.style.position=
"",b.style.bottom="",b.style.width="",f.style.marginBottom="")}var b=this,f=b.previousElementSibling,e=!!document.documentMode;a();window.addEventListener("resize",function(){a()});window.addEventListener("load",function(){a()});return b};(function(a){var b=function(a,b,c){var f;return function(){var g=this,e=arguments;f?clearTimeout(f):c&&a.apply(g,e);f=setTimeout(function(){c||a.apply(g,e);f=null},b||100)}};window[a]=function(c){var f=new CustomEvent(a);return c?this.addEventListener("resize",b(c)):
this.dispatchEvent(f)}})("smartresize");var K=function(){var a=document.createElement("div"),b=document.querySelector("body");a.setAttribute("style","height: 50vh; position: absolute; top: -1000px; left: -1000px;");b.appendChild(a);var f=parseInt(window.innerHeight/2,10),e=parseInt((window.getComputedStyle?getComputedStyle(a,null):a.currentStyle).height,10);b.removeChild(a);return e==f}();m(function(){function a(a){a.style.height=9*p(a.parentNode)/16+"px"}function c(a){setTimeout(function(){b(a,".mbr-parallax-background").forEach(function(a){jarallax&&
(jarallax(a,{speed:.6}),a.style.position="relative")})},0)}function f(a){b(a,"[data-bg-video]").forEach(function(a){var b=a.getAttribute("data-bg-video");if(b){var c=new URLSearchParams(b),f=Number(c.has("t")?c.get("t"):0)||0,g=b.match(/(http:\/\/|https:\/\/|)?(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(shorts\/|video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?/),e=a.querySelector(".mbr-background-video-preview")||document.createElement("div");e.classList.add("mbr-background-video-preview");
e.style.display="none";e.style.backgroundSize="cover";e.style.backgroundPosition="center";a.querySelector(".mbr-background-video-preview")||a.childNodes[0].before(e);var J=function(a,b){var c=window.outerWidth;var g=window.outerHeight;var f=a._opts.width/a._opts.height;var e=Math.ceil(c/f);e<g&&(e=g,c=Math.ceil(e*f));a.setSize(c,e)};if(g&&(/youtu\.?be/g.test(g[3])||/vimeo/g.test(g[3])))if(g&&/youtu\.?be/g.test(g[3])){g[6]=g[6].replace("shorts","embed");b="http"+("https:"===location.protocol?"s":"")+
":";b+="//img.youtube.com/vi/"+g[6]+"/maxresdefault.jpg";var d=new Image;d.onload=function(){if(120===(d.naturalWidth||d.width)){var b=d.src.split("/").pop();switch(b){case "maxresdefault.jpg":d.src=d.src.replace(b,"sddefault.jpg");break;case "sddefault.jpg":d.src=d.src.replace(b,"hqdefault.jpg");break;default:n&&(e.style.backgroundImage='url("images/no-video.jpg")',e.style.display="block")}}else e.style.backgroundImage='url("'+d.src+'")',e.style.display="block";a.querySelector(".mbr-background-video")&&
a.querySelector(".mbr-background-video").remove();b=document.createElement("div");var c=document.createElement("div"),h=document.createElement("div"),v=document.createElement("div");v.classList.add("mbr-video-foreground");v.appendChild(b);h.appendChild(v);c.appendChild(h);b.classList.add("mbr-background-video");a.childNodes[1].before(c);var k=d.naturalHeight,q=d.naturalWidth,F=d.naturalHeight/d.naturalWidth,m=b.parentNode.clientHeight,x=b.parentNode.clientWidth;k=k<m?k:m;q=q>x?q:x;k/q!=F&&(k=q*F);
var l=new YouTubePlayer(b,{modestBranding:!0,autoplay:!0,controls:!1,origin:"*",iv_load_policy:!1,keyboard:!1,captions:!1,annotations:!1,related:!1,start:f});c.style.overflow="hidden";c.style.position="absolute";c.style.width="100%";c.style.height="100%";c.style.top="0";c.style.left="0";h.style.background="#000";h.style.top="0";h.style.right="0";h.style.bottom="0";h.style.left="0";v.style.position="absolute";v.style.top="0";v.style.left="0";v.style.width="100%";v.style.height="100%";v.style.pointerEvents=
"none";b.style.marginTop="0";b.style.maxWidth="initial";b.style.transitionProperty="opacity";b.style.transitionDuration="1000ms";b.style.pointerEvents="none";b.style.position="absolute";b.style.top="0";b.style.left="0";b.style.width="100%";b.style.height="100%";b.parentNode.style.overflow="hidden";b.style.transform="scale(1.2)";l.load(g[6],!0,f);l.play();l.setLoop(!0);l.mute();l.on("ended",function(){return l.play()});J(l)};d.setAttribute("src",b)}else g&&/vimeo/g.test(g[3])&&(c=new XMLHttpRequest,
c.open("GET","https://vimeo.com/api/v2/video/"+g[6]+".json",!0),c.onreadystatechange=function(){if(4===this.readyState)if(200<=this.status&&400>this.status){var a=JSON.parse(this.responseText);e.style.backgroundImage='url("'+a[0].thumbnail_large+'")';e.style.display="block"}else n&&(e.style.backgroundImage='url("images/no-video.jpg")',e.style.display="block")},c.send(),c=null,a.querySelector(".mbr-background-video")&&a.querySelector(".mbr-background-video").remove(),c=document.createElement("div"),
c.classList.add("mbr-background-video"),a.childNodes[1].before(c),b=new Vimeo.Player(c,{id:b,loop:!0,background:!0,responsive:!0,autoplay:!0,byline:!1,title:!1,muted:!0,controls:!1}),c=b.element.parentNode,c.style.overflow="hidden",b.element.style.pointerEvents="none",b.element.style.marginLeft="-"+(b.element.scrollWidth-c.scrollWidth)/2+"px",b.element.style.minHeight="100vh",b.element.style.minWidth="177.77vh");else if(n)e.style.backgroundImage='url("images/video-placeholder.jpg")',e.style.display=
"block";else if(!n){c=document.createElement("video");var h=document.createElement("source");c.append(h);a.childNodes[1].before(c);h.src=b;c.autoplay=!0;c.loop=!0;c.muted=!0;c.setAttribute("muted","");c.playsinline=!0;c.setAttribute("playsinline","");c.style.position="absolute";c.style.left="50%";c.style.top="50%";c.style.bottom="0";c.style.right="0";c.style.minWidth="100%";c.style.minHeight="100%";c.style.transform="translateX(-50%) translateY(-50%)";b="";a.querySelector(".mbr-fallback-image")&&
(b=window.getComputedStyle(a.querySelector(".mbr-fallback-image")).backgroundImage,b=b.match(/\((.*?)\)/)[1].replace(/('|")/g,""),c.setAttribute("poster",b));c.parentNode.style.overflow="hidden"}}})}document.querySelector("html").classList.add(t()?"mobile":"desktop");window.addEventListener("scroll",function(){document.querySelectorAll(".mbr-navbar--sticky").forEach(function(a){var b=10<window.scrollTop?"add":"remove";a.classList[b]("mbr-navbar--stuck");if(!a.classList.contains(".mbr-navbar--open"))a.classList[b]("mbr-navbar--short")})});
t()&&navigator.userAgent.match(/Chrome/i)?function(a,b){var c=[a,a];c[b>a?0:1]=b;window.smartresize(function(){var a=window.innerHeight;0>c.indexOf(a)&&(a=c[window.innerWidth>a?1:0]);var b=document.querySelector(".mbr-section--full-height");b&&(b.style.height=a+"px")})}(window.innerWidth,window.innerHeight):K||(window.smartresize(function(){var a=document.querySelector(".mbr-section--full-height");a&&(a.style.height=window.innerHeight+"px")}),document.addEventListener("add.cards",function(a){document.querySelector("html").classList.contains("mbr-site-loaded")&&
b(a.target,".mbr-section--full-height").length&&window.dispatchEvent(new CustomEvent("resize"))}));window.addEventListener("smartresize",function(){document.querySelectorAll(".mbr-section--16by9").forEach(a)});if(r)h(document).on("add.cards changeParameter.cards",function(c){var g=b(c.target,".mbr-section--16by9");g.length?g.forEach(function(b){b.setAttribute("data-16by9","true");a(b)}):b(c.target,"[data-16by9]").forEach(function(a){a.styles.height="";a.removeAttribute("data-16by9")})});if("undefined"!==
typeof jarallax&&!t()){window.addEventListener("update.parallax",function(a){setTimeout(function(){if(a){var a=document.querySelector(".mbr-parallax-background");a.jarallax("coverImage");a.jarallax("clipContainer");a.jarallax("onScroll")}},0)});if(n){if(!r)return;h(document).on("add.cards",function(a){c(a.target);h(window).trigger("update.parallax")});h(document).on("changeParameter.cards",function(a,b,g,f){if("bg"===b)switch(b=a.target,jarallax&&jarallax(b,"destroy"),b.style.position="",h(a.target).find(".mbr-background-video-preview").remove(),
h(a.target).find(".mbr-background-video").remove(),f){case "type":!0===g.parallax&&c(a.target);break;case "value":"image"===g.type&&!0===g.parallax&&c(a.target);break;case "parallax":!0===g.parallax&&c(a.target)}h(window).trigger("update.parallax")})}else c(document.body);window.addEventListener("shown.bs.tab",function(){window.dispatchEvent(new CustomEvent("update.parallax"))})}var e,g,x=0,q=null,m=!t();window.addEventListener("scroll",function(){g&&clearTimeout(g);var a=document.documentElement.scrollTop,
b=a<=x||m;x=a;if(q){var c=a>q.breakPoint;b?c!=q.fixed&&(m?(q.fixed=c,q.elm.classList.toggle("is-fixed")):g=setTimeout(function(){q.fixed=c;q.elm.classList.toggle("is-fixed")},40)):(q.fixed=!1,q.elm.classList.remove("is-fixed"))}});if(r)h(document).on("add.cards delete.cards",function(a){e&&clearTimeout(e);e=setTimeout(function(){q&&(q.fixed=!1,q.elm.classList.remove("is-fixed"));var a=document.querySelector(".mbr-fixed-top");a&&(q={breakPoint:d(a).top+3*k(a),fixed:!1,elm:a},a.dispatchEvent(new CustomEvent("scroll")))},
650)});window.smartresize(function(){document.querySelectorAll(".mbr-embedded-video").forEach(function(a){a.style.height=(p(a)*parseInt(a.getAttribute("height")||315)/parseInt(a.getAttribute("width")||560)).toFixed()+"px"})});if(r)h(document).on("add.cards",function(a){document.querySelector("html").classList.contains("mbr-site-loaded")&&b(a.target,"iframe").length&&window.dispatchEvent(new CustomEvent("resize"))});if(n){if(!r)return;var l=[];h(document).on("add.cards",function(a){a.target!==document&&
!l.some(function(b){return b===a.target})&&a.target.hasAttribute("mbr-data-bg-video")&&(l.push(a.target),f(a.target))})}else f(document.body);if(n)h(document).on("changeParameter.cards",function(a,b,c,g){if("bg"===b)switch(g){case "type":"video"===c.type&&f(a.target);break;case "value":"video"===c.type&&f(a.target)}});document.querySelector("html").classList.add("mbr-site-loaded");window.dispatchEvent(new CustomEvent("resize"));window.dispatchEvent(new CustomEvent("scroll"));n||document.addEventListener("click",
function(a){try{var b=a.target;if(!b.parents().some(function(a){a.classList.contains("carousel")})){do if(b.hash){var c=/#bottom|#top/g.test(b.hash);document.querySelectorAll(c?"body":b.hash).forEach(function(c){a.preventDefault();var g=document.querySelector(".navbar-fixed-top");g="#bottom"==b.hash?k(c)-window.innerHeight:d(c).top-(g?60:0);c.classList.contains("panel-collapse")||c.classList.contains("tab-pane")||b.classList.contains("carousel-control")||b.parents(".carousel-controls").length||window.scrollTo({top:g,
left:0,behavior:"smooth"})});break}while(b=b.parentNode)}}catch(M){}});document.querySelectorAll(".cols-same-height .mbr-figure").forEach(function(a){function b(){c.style.width="";c.style.maxWidth="";c.style.marginLeft="";if(e&&f){var b=e/f;a.style.position="absolute";a.style.top="0";a.style.left="0";a.style.right="0";a.style.bottom="0";var d=k(g)/p(g);d>b&&(b=100*(d-b)/b,c.style.width=b+100+"%",c.style.maxWidth=b+100+"%",c.style.marginLeft=-b/2+"%")}}var c=a.querySelector("img"),g=a.parentNode,f=
c.width,e=c.height;c.addEventListener("load",function(){f=c.width;e=c.height;b()},{once:!0});window.addEventListener("resize",b);b()})});if(!n){if(r&&h.fn.socialLikes)h(document).on("add.cards",function(a){b(a.target,".mbr-social-likes").forEach(function(a){a.addEventListener("counter.social-likes",function(a,b,c){999<c&&a.target.querySelectorAll(".social-likes__counter").forEach(function(a){a.innerHTML=Math.floor(c/1E3)+"k"})});a.socialLikes({initHtml:!1})})});Array.from(document.body.children).filter(function(a){return!a.matches("style, script")}).forEach(function(a){a.classList.contains("mbr-reveal")&&
a.addEventListener("add.cards",function(){a.footerReveal()})});m(function(){if(!t()&&document.querySelectorAll("input[name=animation]").length){var a=function(){var a=document.documentElement.scrollTop||document.body.scrollTop,c=a+window.innerHeight-100;e.forEach(function(g){var e=g.offsetHeight,d=f(g);(d+e>=a&&d-50<=c||b(g))&&g.classList.contains("hidden")&&(g.classList.remove("hidden"),g.classList.add("animate__fadeIn"),g.classList.add("animate__delay-1s"),g.addEventListener("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",
function(){g.classList.remove("animate__animated animate__delay-1s animate__fadeIn")},{once:!0}))})},b=function(a){if(a.parents(".carousel-item").some(function(a){return"none"!==getComputedStyle(a,null).display}))return!1;var b=a.parents(".carousel-item").parentNode;if(!b||b.querySelectorAll(".carousel-item.active .hidden.animate__animated").length)return!1;if(1<b.getAttribute("data-visible")){var c=b.getAttribute("data-visible");if(a.parents().some(function(a){return a.matches(".cloneditem-"+(c-
1))})&&a.parents(".cloneditem-"+(c-1)).some(function(a){return a.getAttribute("data-cloned-index")>=c}))return!0;a.classList.remove("animate__animated animate__delay-1s hidden");return!1}return!0},f=function(a){var b=0;do b+=a.offsetTop||0,a=a.offsetParent;while(a);return b};document.querySelectorAll("input[name=animation]").forEach(function(a){a.remove()});var e=Array.from(document.querySelectorAll("p, h1, h2, h3, h4, h5, a, button, small, img, li, blockquote, .mbr-author-name, em, label, input, select, textarea, .input-group, .form-control, .iconbox, .btn-social, .mbr-figure, .mbr-map, .mbr-testimonial .card-block, .mbr-price-value, .mbr-price-figure, .dataTable, .dataTables_info, .item"));
e=e.filter(function(a){if(!a.parents().filter(function(a){if(a.matches("a, p, .navbar, .mbr-arrow, footer, .iconbox, .mbr-slider, .mbr-gallery, .mbr-testimonial .card-block, #cookiesdirective, .mbr-wowslider, .accordion, .tab-content, .engine, #scrollToTop, .modal, .item"))return!0}).length)return!0});e=e.filter(function(a){if(!a.parents().filter(function(b){return b.matches("form")&&!a.matches("li")}).length)return!0});e.forEach(function(a){a.classList.add("hidden");a.classList.add("animate__animated");
a.classList.add("animate__delay-1s")});window.addEventListener("scroll",a);window.addEventListener("resize",a);window.dispatchEvent(new CustomEvent("scroll"))}})}m(function(){if(document.querySelectorAll(".mbr-arrow-up").length){var a=document.querySelector("#scrollToTop");a.style.display="none";window.addEventListener("scroll",function(){(document.documentElement.scrollTop||document.body.scrollTop)>Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,
document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight)/2-document.documentElement.clientHeight/2||window.scrollY>window.innerHeight?w(a):l(a)});a.addEventListener("click",function(){window.scrollTo({top:0,left:0,behavior:"smooth"});return!1})}});if(!n){var u=document.querySelector(".mbr-arrow");u&&u.addEventListener("click",function(a){a=a.target.closest("section").nextElementSibling;a.classList.contains("engine")&&(a=a.closest("section").nextElementSibling);
window.scrollTo(0,d(a).top)})}document.querySelectorAll("nav.navbar").length&&(u=k(document.querySelector("nav.navbar")),document.querySelector(".mbr-after-navbar.mbr-fullscreen")&&(document.querySelector(".mbr-after-navbar.mbr-fullscreen").style.paddingTop=u+"px"));if(!n&&(0<window.navigator.userAgent.indexOf("MSIE ")||navigator.userAgent.match(/Trident.*rv:11\./)))h(document).on("add.cards",function(a){var b=a.target;b.classList.contains("mbr-fullscreen")&&(a=function(){b.style.height="auto";b.offsetHeight<=
window.innerHeight&&(b.style.height="1px")},window.addEventListener("load",a),window.addEventListener("resize",a));if(b.classList.contains("mbr-slider")||b.classList.contains("mbr-gallery"))b.querySelectorAll(".carousel-indicators").forEach(function(a){a.classList.add("ie-fix");a.querySelectorAll("li").forEach(function(a){a.style.display="inline-block";a.style.width="30px"})}),b.classList.contains("mbr-slider")&&b.querySelectorAll(".full-screen .slider-fullscreen-image").forEach(function(a){a.style.height=
"1px"})});m(function(){if(!n){var a=function(a){a.target&&("VIDEO"==a.target.tagName?(a.preventDefault(),a.stopPropagation()):b(a.target))},b=function(b){var c=b.parents("section")[0].querySelector("iframe"),g=c.getAttribute("src");b.parents("section").forEach(function(a){a.style.zIndex="5000"});if(g){if(-1!==g.indexOf("youtu")&&c.contentWindow.postMessage('{"event":"command","func":"playVideo","args":""}',"*"),-1!==g.indexOf("vimeo")){var f=new Vimeo.Player(c);f.play()}}else{var d=c.parentNode.querySelector("video");
d&&d.play&&d.play()}var h=b.parents("section")[0],k=h.querySelector(h.querySelector("[data-modal]").getAttribute("data-modal"));k.style.display="table";k.addEventListener("click",function(b){"VIDEO"!==b.target.tagName&&(g?(-1!==g.indexOf("youtu")&&c.contentWindow.postMessage('{"event":"command","func":"pauseVideo","args":""}',"*"),-1!==g.indexOf("vimeo")&&f.pause()):(b=c.parentNode.querySelector("video"))&&b.pause&&b.pause(),k.style.display="none",k.removeEventListener("click",a),h.style.zIndex="0")})};
document.querySelectorAll(".modalWindow-video > iframe").forEach(function(a){var b=a.getAttribute("data-src");if(b){a.removeAttribute("data-src");var c=b.match(/(http:\/\/|https:\/\/|)?(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(shorts\/|video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?/);if(-1!==b.indexOf("youtu"))a.setAttribute("src","https://youtube.com/embed/"+c[6]+"?rel=0&enablejsapi=1");else if(-1!==b.indexOf("vimeo"))a.setAttribute("src","https://player.vimeo.com/video/"+
c[6]+"?autoplay=0&loop=0");else if(/\.mp4|\.webm|\.ogg|\.ogv|\.m4a|\.m4v/.test(b)){c=document.createElement("video");c.onloadeddata=function(a){a.target.style.height=a.target.videoHeight>a.target.videoWidth?window.innerHeight-.2*window.innerHeight+"px":"100%"};var f=a.parents("section")[0].querySelector("img");f&&c.setAttribute("poster",f.src);c.setAttribute("controls","");c.setAttribute("playsinline","");c.setAttribute("loop","");c.setAttribute("src",b);a.style.display="none";c.style.width="100%";
a.after(c)}}});document.querySelector("[data-modal]")&&document.querySelectorAll("[data-modal]").forEach(function(b){b.addEventListener("click",a)})}});if(!n){u=document.querySelectorAll(".dropdown-toggle.show");var A=document.querySelectorAll(".dropdown-menu.show, .dropdown.open"),L=document.querySelectorAll(".dropdown.open");u.forEach(function(a){a.classList.remove("show");a.ariaExpanded="false"});A.forEach(function(a){return a.classList.remove("show")});L.forEach(function(a){return a.classList.remove("open")});
!t()&&(u=document.querySelector("section.menu"))&&(A=window.innerWidth,!u.querySelector(".navbar").classList.contains("collapsed")&&991<A&&(u.querySelectorAll("ul.navbar-nav li.dropdown").forEach(function(a){a.addEventListener("mouseover",function(){a.classList.contains("open")||a.querySelector("a").parentNode.classList.toggle("open")});a.addEventListener("mouseout",function(){a.classList.contains("open")&&a.querySelector("a").parentNode.classList.toggle("open")})}),u.querySelectorAll("ul.navbar-nav li.dropdown .dropdown-menu .dropdown").forEach(function(a){a.addEventListener("mouseover",
function(){a.classList.contains("open")||a.classList.toggle("open")});a.addEventListener("mouseout",function(){a.classList.contains("open")&&a.classList.toggle("open")})})))}n||("undefined"===typeof window.initClientPlugin&&0!=document.body.querySelectorAll(".clients").length&&(window.initClientPlugin=!0,document.body.querySelectorAll(".clients").forEach(function(a){a.getAttribute("data-isinit")||(y(a),G(a))})),"undefined"===typeof window.initPopupBtnPlugin&&0!=document.body.querySelectorAll("section.popup-btn-cards").length&&
(window.initPopupBtnPlugin=!0,document.querySelectorAll("section.popup-btn-cards .card-wrapper").forEach(function(a){a.classList.add("popup-btn")})),"undefined"===typeof window.initTestimonialsPlugin&&0!=document.body.querySelectorAll(".testimonials-slider").length&&(window.initTestimonialsPlugin=!0,document.querySelectorAll(".testimonials-slider").forEach(function(a){y(a)})),"undefined"===typeof window.initSwitchArrowPlugin&&(window.initSwitchArrowPlugin=!0,m(function(){0!=document.querySelectorAll(".accordionStyles").length&&
document.querySelectorAll('.accordionStyles > .card > .card-header > a[role="button"]').forEach(function(a){a.classList.contains("collapsed")||a.classList.add("collapsed")})}),document.querySelectorAll('.accordionStyles > .card > .card-header > a[role="button"]').forEach(function(a){a.addEventListener("click",function(){var b=a.closest(".accordionStyles").getAttribute("id"),f=a.closest(".card").querySelector(".panel-collapse"),e=a.querySelector("span.sign")?a.querySelector("span.sign"):a.querySelector("span.mbr-iconfont");
!f.classList.contains("collapsing")||-1==b.indexOf("toggle")&&-1==b.indexOf("accordion")||(a.classList.contains("collapsed")?(e.classList.remove("mbri-arrow-up"),e.classList.add("mbri-arrow-down")):(e.classList.remove("mbri-arrow-down"),e.classList.add("mbri-arrow-up")),-1!=b.indexOf("accordion")&&(b=a.closest(".accordionStyles"),Array.from(b.children).filter(function(a){return a.querySelector("span.sign")!==e}).forEach(function(a){a=a.querySelector("span.sign")?a.querySelector("span.sign"):a.querySelector("span.mbr-iconfont");
a.classList.remove("mbri-arrow-up");a.classList.add("mbri-arrow-down")})))})})),0!=document.querySelectorAll(".mbr-slider.carousel").length&&document.querySelectorAll(".mbr-slider.carousel").forEach(function(a){var b=a.querySelectorAll(".carousel-control"),f=a.querySelectorAll(".carousel-indicators li"),e=function(a){a.stopPropagation();a.preventDefault()};a.addEventListener("slide.bs.carousel",function(){b.forEach(function(a){a.addEventListener("click",e)});f.forEach(function(a){a.addEventListener("click",
e)});r&&h(a).carousel({keyboard:!1})});a.addEventListener("slid.bs.carousel",function(){b.forEach(function(a){a.removeEventListener("click",e)});f.forEach(function(a){a.removeEventListener("click",e)});r&&h(a).carousel({keyboard:!0});1<a.querySelectorAll(".carousel-item.active").length&&(a.querySelectorAll(".carousel-item.active")[1].classList.remove("active"),a.querySelectorAll(".carousel-control li.active")[1].classList.remove("active"))})}));if(n){if(!r)return;h(document).on("add.cards",function(a){h(a.target).find(".form-with-styler").length&&
(a=h(a.target).find(".form-with-styler"),h(a).find('select:not("[multiple]")').each(function(){h(this).styler&&h(this).styler()}),h(a).find("input[type=number]").each(function(){h(this).styler&&(h(this).styler(),h(this).parent().parent().removeClass("form-control"))}),h(a).find("input[type=date]").each(function(){h(this).datetimepicker&&h(this).datetimepicker({format:"Y-m-d",timepicker:!1})}),h(a).find("input[type=time]").each(function(){h(this).datetimepicker&&h(this).datetimepicker({format:"H:i",
datepicker:!1})}))})}document.querySelectorAll('input[type="range"]').forEach(function(a){a.addEventListener("change",function(a){a.target.parents(".form-group").forEach(function(b){b.querySelector(".value").innerHTML=a.target.value})})});if(n)h(document).on("add.cards changeParameter.cards",function(a,b){"undefined"!==typeof CircularProgressBar&&new CircularProgressBar("pie_progress");b?I(a.target,b):a.target.querySelectorAll(".pie_progress").length&&a.target.querySelectorAll(".pie_progress").forEach(function(a){C(a)})});
else document.querySelectorAll(".pie_progress").length&&("undefined"!==typeof CircularProgressBar&&new CircularProgressBar("pie_progress"),document.querySelectorAll(".pie_progress").forEach(function(a){C(a)}));if(n&&r)h(document).on("add.cards",function(a){h(a.target).hasClass("testimonials-slider")&&y(a.target)}).on("changeParameter.cards",function(a,b,d){"testimonialsSlides"===b&&0==h(a.target).find(".carousel-item.active").length&&B(a.target)});else"undefined"===typeof window.initTestimonialsPlugin&&
(window.initTestimonialsPlugin=!0,document.querySelectorAll(".testimonials-slider").forEach(function(a){y(a)}));m(function(){n||Array.from(document.body.children).filter(function(a){return!a.matches("style, script")}).forEach(function(a){if(window.Event&&"function"===typeof window.Event)var b=new Event("add.cards");else b=document.createEvent("CustomEvent"),b.initEvent("add.cards",!0,!0);a.dispatchEvent(b)})});m(function(){window.addEventListener("scroll",function(){var a=document.querySelector(".navbar-dropdown"),
b=document.querySelector(".navbar-collapse");if(a&&!a.classList.contains("opacityScrollOff")){var d=1<document.documentElement.scrollTop;a.classList.toggle("opacityScroll",!d);b.classList.toggle("opacityScroll",!d)}})});if(n)h(document).on("add.cards",D);else window.addEventListener("DOMContentLoaded",D);if(n)h(document).on("add.cards",E);else window.addEventListener("DOMContentLoaded",E)})();
