/*! @vimeo/player v2.15.3 | (c) 2021 Vimeo | MIT License | https://github.com/vimeo/player.js */
/*
 @vimeo/player v2.15.3 | (c) 2021 Vimeo | MIT License | https://github.com/vimeo/player.js */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,k){b!=Array.prototype&&b!=Object.prototype&&(b[f]=k.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var f=0;return $jscomp.iteratorPrototype(function(){return f<b.length?{done:!1,value:b[f++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();var f=b[Symbol.iterator];return f?f.call(b):$jscomp.arrayIterator(b)};$jscomp.owns=function(b,f){return Object.prototype.hasOwnProperty.call(b,f)};
$jscomp.polyfill=function(b,f,k,h){if(f){k=$jscomp.global;b=b.split(".");for(h=0;h<b.length-1;h++){var g=b[h];g in k||(k[g]={});k=k[g]}b=b[b.length-1];h=k[b];f=f(h);f!=h&&null!=f&&$jscomp.defineProperty(k,b,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("WeakMap",function(b){function f(a){$jscomp.owns(a,h)||$jscomp.defineProperty(a,h,{value:{}})}function k(a){var e=Object[a];e&&(Object[a]=function(a){f(a);return e(a)})}if(function(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),e=Object.seal({}),l=new b([[a,2],[e,3]]);if(2!=l.get(a)||3!=l.get(e))return!1;l["delete"](a);l.set(e,4);return!l.has(a)&&4==l.get(e)}catch(x){return!1}}())return b;var h="$jscomp_hidden_"+Math.random().toString().substring(2);k("freeze");k("preventExtensions");
k("seal");var g=0,m=function(a){this.id_=(g+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var e;!(e=a.next()).done;)e=e.value,this.set(e[0],e[1])}};m.prototype.set=function(a,e){f(a);if(!$jscomp.owns(a,h))throw Error("WeakMap key fail: "+a);a[h][this.id_]=e;return this};m.prototype.get=function(a){return $jscomp.owns(a,h)?a[h][this.id_]:void 0};m.prototype.has=function(a){return $jscomp.owns(a,h)&&$jscomp.owns(a[h],this.id_)};m.prototype["delete"]=
function(a){return $jscomp.owns(a,h)&&$jscomp.owns(a[h],this.id_)?delete a[h][this.id_]:!1};return m},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function f(){this.batch_=null}function k(a){return a instanceof g?a:new g(function(e,b){e(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;f.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};f.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var h=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(a){h(a,
0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var e=0;e<a.length;++e){var b=a[e];delete a[e];try{b()}catch(x){this.asyncThrow_(x)}}}this.batch_=null};f.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var g=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var e=this.createResolveAndReject_();try{a(e.resolve,e.reject)}catch(l){e.reject(l)}};g.prototype.createResolveAndReject_=
function(){function a(a){return function(g){b||(b=!0,a.call(e,g))}}var e=this,b=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};g.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof g)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var e=null!=a;break a;case "function":e=!0;break a;default:e=!1}e?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};g.prototype.resolveToNonPromiseObj_=function(a){var e=
void 0;try{e=a.then}catch(l){this.reject_(l);return}"function"==typeof e?this.settleSameAsThenable_(e,a):this.fulfill_(a)};g.prototype.reject_=function(a){this.settle_(2,a)};g.prototype.fulfill_=function(a){this.settle_(1,a)};g.prototype.settle_=function(a,e){if(0!=this.state_)throw Error("Cannot settle("+a+", "+e|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=e;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,e=0;e<a.length;++e)a[e].call(),a[e]=null;this.onSettledCallbacks_=null}};var m=new f;g.prototype.settleSameAsPromise_=function(a){var e=this.createResolveAndReject_();a.callWhenSettled_(e.resolve,e.reject)};g.prototype.settleSameAsThenable_=function(a,e){var b=this.createResolveAndReject_();try{a.call(e,b.resolve,b.reject)}catch(x){b.reject(x)}};g.prototype.then=function(a,e){function b(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(B){k(B)}}:b}var f,k,h=new g(function(a,
b){f=a;k=b});this.callWhenSettled_(b(a,f),b(e,k));return h};g.prototype["catch"]=function(a){return this.then(void 0,a)};g.prototype.callWhenSettled_=function(a,b){function e(){switch(f.state_){case 1:a(f.result_);break;case 2:b(f.result_);break;default:throw Error("Unexpected state: "+f.state_);}}var f=this;null==this.onSettledCallbacks_?m.asyncExecute(e):this.onSettledCallbacks_.push(function(){m.asyncExecute(e)})};g.resolve=k;g.reject=function(a){return new g(function(b,f){f(a)})};g.race=function(a){return new g(function(b,
f){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())k(g.value).callWhenSettled_(b,f)})};g.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?k([]):new g(function(a,e){function g(b){return function(e){h[b]=e;l--;0==l&&a(h)}}var h=[],l=0;do h.push(void 0),l++,k(f.value).callWhenSettled_(g(h.length-1),e),f=b.next();while(!f.done)})};return g},"es6","es3");
!function(b,f){"object"==typeof exports&&"undefined"!=typeof module?module.exports=f():"function"==typeof define&&define.amd?define(f):((b="undefined"!=typeof globalThis?globalThis:b||self).Vimeo=b.Vimeo||{},b.Vimeo.Player=f())}(this,function(){function b(a,t){for(var c=0;c<t.length;c++){var d=t[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}function f(d,a){return 0===d.indexOf(a.toLowerCase())?d:"".concat(a.toLowerCase()).concat(d.substr(0,
1).toUpperCase()).concat(d.substr(1))}function k(a){return/^(https?:)?\/\/((player|www)\.)?vimeo\.com(?=$|\/)/.test(a)}function h(a){var d=0<arguments.length&&void 0!==a?a:{},c=d.id;d=d.url;d=c||d;if(!d)throw Error("An id or url must be passed, either in an options object or as a data-vimeo-id or data-vimeo-url attribute.");if(!isNaN(parseFloat(d))&&isFinite(d)&&Math.floor(d)==d)return"https://vimeo.com/".concat(d);if(k(d))return d.replace("http:","https:");if(c)throw new TypeError("\u201c".concat(c,
"\u201d is not a valid video id."));throw new TypeError("\u201c".concat(d,"\u201d is not a vimeo.com url."));}function g(){if(void 0===this)throw new TypeError("Constructor WeakMap requires 'new'");if(q(this,"_id","_WeakMap_"+Math.random().toString().substring(2)+"."+Math.random().toString().substring(2)),0<arguments.length)throw new TypeError("WeakMap iterable is not supported");}function m(d,a){if(Object(d)!==d||!J.call(d,"_id"))throw new TypeError(a+" method called on incompatible receiver "+typeof d);
}function a(d,a,c){var u=r.get(d.element)||{};a in u||(u[a]=[]);u[a].push(c);r.set(d.element,u)}function e(a,b){return(r.get(a.element)||{})[b]||[]}function l(a,b,c){var d=r.get(a.element)||{};if(!d[b])return!0;if(!c)return d[b]=[],r.set(a.element,d),!0;c=d[b].indexOf(c);return-1!==c&&d[b].splice(c,1),r.set(a.element,d),d[b]&&0===d[b].length}function x(a,b){return N.reduce(function(c,d){var b=a.getAttribute("data-vimeo-".concat(d));return!b&&""!==b||(c[d]=""===b?1:b),c},1<arguments.length&&void 0!==
b?b:{})}function D(a,b){var c=a.html;if(!b)throw new TypeError("An element must be provided");if(null!==b.getAttribute("data-vimeo-initialized"))return b.querySelector("iframe");var d=document.createElement("div");return d.innerHTML=c,b.appendChild(d.firstChild),b.setAttribute("data-vimeo-initialized","true"),b.querySelector("iframe")}function I(a,b,c){var d=1<arguments.length&&void 0!==b?b:{},e=2<arguments.length?c:void 0;return new Promise(function(c,b){if(!k(a))throw new TypeError("\u201c".concat(a,
"\u201d is not a vimeo.com url."));var u="https://vimeo.com/api/oembed.json?url=".concat(encodeURIComponent(a)),t;for(t in d)d.hasOwnProperty(t)&&(u+="&".concat(t,"=").concat(encodeURIComponent(d[t])));var f=new ("XDomainRequest"in window?XDomainRequest:XMLHttpRequest);f.open("GET",u,!0);f.onload=function(){if(404!==f.status)if(403!==f.status)try{var d=JSON.parse(f.responseText);if(403===d.domain_status_code)return D(d,e),void b(Error("\u201c".concat(a,"\u201d is not embeddable.")));c(d)}catch(A){b(A)}else b(Error("\u201c".concat(a,
"\u201d is not embeddable.")));else b(Error("\u201c".concat(a,"\u201d was not found.")))};f.onerror=function(){var c=f.status?" (".concat(f.status,")"):"";b(Error("There was an error fetching the embed code from Vimeo".concat(c,".")))};f.send()})}function H(a){if("string"==typeof a)try{a=JSON.parse(a)}catch(t){return console.warn(t),{}}return a}function z(a,b,c){var d,e;a.element.contentWindow&&a.element.contentWindow.postMessage&&(d={method:b},void 0!==c&&(d.value=c),8<=(e=parseFloat(navigator.userAgent.toLowerCase().replace(/^.*msie (\d+).*$/,
"$1")))&&10>e&&(d=JSON.stringify(d)),a.element.contentWindow.postMessage(d,a.origin))}function M(a,b){var c,d,f=[];(b=H(b)).event?("error"===b.event&&e(a,b.data.method).forEach(function(c){var d=Error(b.data.message);d.name=b.data.name;c.reject(d);l(a,b.data.method,c)}),f=e(a,"event:".concat(b.event)),c=b.data):!b.method||(d=function(c,a){var b=e(c,a);if(1>b.length)return!1;b=b.shift();return l(c,a,b),b}(a,b.method))&&(f.push(d),c=b.value);f.forEach(function(b){try{if("function"==typeof b)return void b.call(a,
c);b.resolve(c)}catch(V){}})}var B="undefined"!=typeof global&&"[object global]"==={}.toString.call(global),E=void 0!==Array.prototype.indexOf,Q="undefined"!=typeof window&&void 0!==window.postMessage;if(!(B||E&&Q))throw Error("Sorry, the Vimeo Player API is not available in this browser.");var K,J,q,C="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{};(K="undefined"!=typeof self?self:"undefined"!=typeof window?
window:C).WeakMap||(J=Object.prototype.hasOwnProperty,q=function(a,b,c){Object.defineProperty?Object.defineProperty(a,b,{configurable:!0,writable:!0,value:c}):a[b]=c},K.WeakMap=(q(g.prototype,"delete",function(a){if(m(this,"delete"),Object(a)!==a)return!1;var b=a[this._id];return!(!b||b[0]!==a)&&(delete a[this._id],!0)}),q(g.prototype,"get",function(a){if(m(this,"get"),Object(a)===a){var b=a[this._id];return b&&b[0]===a?b[1]:void 0}}),q(g.prototype,"has",function(a){if(m(this,"has"),Object(a)!==a)return!1;
var b=a[this._id];return!(!b||b[0]!==a)}),q(g.prototype,"set",function(a,b){if(m(this,"set"),Object(a)!==a)throw new TypeError("Invalid value used as weak map key");var c=a[this._id];return c&&c[0]===a?c[1]=b:q(a,this._id,[a,b]),this}),q(g,"_polyfill",!0),g));var L,v=(function(a){C.Promise=C.Promise||function(){function a(a,c){this.fn=a;this.self=c;this.next=void 0}function c(a,c){m.add(a,c);A=A||w(m.drain)}function b(a){var c,b=typeof a;return null==a||"object"!=b&&"function"!=b||(c=a.then),"function"==
typeof c&&c}function d(){for(var a=0;a<this.chain.length;a++){var c=void 0,d=void 0,e=1===this.state?this.chain[a].success:this.chain[a].failure,f=this.chain[a];try{!1===e?f.reject(this.msg):(d=!0===e?this.msg:e.call(void 0,this.msg))===f.promise?f.reject(TypeError("Promise-chain cycle")):(c=b(d))?c.call(d,f.resolve,f.reject):f.resolve(d)}catch(U){f.reject(U)}!0}this.chain.length=0}function e(a){var u,g=this;if(!g.triggered){g.triggered=!0;g.def&&(g=g.def);try{(u=b(a))?c(function(){var c=new h(g);
try{u.call(a,function(){e.apply(c,arguments)},function(){f.apply(c,arguments)})}catch(T){f.call(c,T)}}):(g.msg=a,g.state=1,0<g.chain.length&&c(d,g))}catch(S){f.call(new h(g),S)}}}function f(a){var b=this;b.triggered||(b.triggered=!0,b.def&&(b=b.def),b.msg=a,b.state=2,0<b.chain.length&&c(d,b))}function g(a,c,b,d){for(var f=0;f<c.length;f++)!function(f){a.resolve(c[f]).then(function(a){b(f,a)},d)}(f)}function h(a){this.def=a;this.triggered=!1}function k(a){this.promise=a;this.state=0;this.triggered=
!1;this.chain=[];this.msg=void 0}function l(a){if("function"!=typeof a)throw TypeError("Not a function");if(0!==this.__NPO__)throw TypeError("Not a promise");this.__NPO__=1;var b=new k(this);this.then=function(a,f){var e={success:"function"!=typeof a||a,failure:"function"==typeof f&&f};return e.promise=new this.constructor(function(a,c){if("function"!=typeof a||"function"!=typeof c)throw TypeError("Not a function");e.resolve=a;e.reject=c}),b.chain.push(e),0!==b.state&&c(d,b),e.promise};this["catch"]=
function(a){return this.then(void 0,a)};try{a.call(void 0,function(a){e.call(b,a)},function(a){f.call(b,a)})}catch(R){f.call(b,R)}}var A,m,p,r,q,v=Object.prototype.toString,w="undefined"!=typeof setImmediate?function(a){return setImmediate(a)}:setTimeout;try{Object.defineProperty({},"x",{});var n=function(a,c,b,d){return Object.defineProperty(a,c,{value:b,writable:!0,configurable:!1!==d})}}catch(W){n=function(a,c,b){return a[c]=b,a}}var x=n({},"constructor",l,!(m={add:function(c,b){q=new a(c,b);r?
r.next=q:p=q;r=q;q=void 0},drain:function(){var a=p;for(p=r=A=void 0;a;)a.fn.call(a.self),a=a.next}}));return n(l.prototype=x,"__NPO__",0,!1),n(l,"resolve",function(a){return a&&"object"==typeof a&&1===a.__NPO__?a:new this(function(c,b){if("function"!=typeof c||"function"!=typeof b)throw TypeError("Not a function");c(a)})}),n(l,"reject",function(a){return new this(function(c,b){if("function"!=typeof c||"function"!=typeof b)throw TypeError("Not a function");b(a)})}),n(l,"all",function(a){var c=this;
return"[object Array]"!=v.call(a)?c.reject(TypeError("Not an array")):0===a.length?c.resolve([]):new c(function(b,d){if("function"!=typeof b||"function"!=typeof d)throw TypeError("Not a function");var f=a.length,e=Array(f),u=0;g(c,a,function(a,c){e[a]=c;++u===f&&b(e)},d)})}),n(l,"race",function(a){var c=this;return"[object Array]"!=v.call(a)?c.reject(TypeError("Not an array")):new c(function(b,d){if("function"!=typeof b||"function"!=typeof d)throw TypeError("Not a function");g(c,a,function(a,c){b(c)},
d)})}),l}();a.exports&&(a.exports=C.Promise)}(L={exports:{}}),L.exports),r=new WeakMap,N="autopause autoplay background byline color controls dnt height id loop maxheight maxwidth muted playsinline portrait responsive speed texttrack title transparent url width".split(" "),w,F,n,y=new WeakMap,G=new WeakMap,p={};E=function(){function d(c){var b,f,e=this,g=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");if(!0,
window.jQuery&&c instanceof jQuery&&(1<c.length&&window.console&&console.warn&&console.warn("A jQuery object with multiple elements was passed, using the first element."),c=c[0]),"undefined"!=typeof document&&"string"==typeof c&&(c=document.getElementById(c)),b=c,!(b&&1===b.nodeType&&"nodeName"in b&&b.ownerDocument&&b.ownerDocument.defaultView))throw new TypeError("You must pass either a valid element or a valid id.");if("IFRAME"===c.nodeName||(f=c.querySelector("iframe"))&&(c=f),"IFRAME"===c.nodeName&&
!k(c.getAttribute("src")||""))throw Error("The player element passed isn\u2019t a Vimeo embed.");if(y.has(c))return y.get(c);this._window=c.ownerDocument.defaultView;this.element=c;this.origin="*";var t;b=new v(function(a,b){var d;e._onMessage=function(c){if(k(c.origin)&&e.element.contentWindow===c.source){"*"===e.origin&&(e.origin=c.origin);if((c=H(c.data))&&"error"===c.event&&c.data&&"ready"===c.data.method){var d=Error(c.data.message);return d.name=c.data.name,void b(d)}d=c&&"ping"===c.method;
if(c&&"ready"===c.event||d)return e.element.setAttribute("data-ready","true"),void a();M(e,c)}};e._window.addEventListener("message",e._onMessage);"IFRAME"!==e.element.nodeName&&I(h(d=x(c,g)),d,c).then(function(a){var b,d,f=D(a,c);return e.element=f,e._originalElement=c,b=c,d=r.get(b),r.set(f,d),r["delete"](b),y.set(e.element,e),a})["catch"](b)});return G.set(this,b),y.set(this.element,this),"IFRAME"===this.element.nodeName&&z(this,"ping"),p.isEnabled&&(t=function(){return p.exit()},p.on("fullscreenchange",
function(){(p.isFullscreen?a:l)(e,"event:exitFullscreen",t);e.ready().then(function(){z(e,"fullscreenchange",p.isFullscreen)})})),this}var g;return g=[{key:"callMethod",value:function(c,b){var d=this,e=1<arguments.length&&void 0!==b?b:{};return new v(function(b,f){return d.ready().then(function(){a(d,c,{resolve:b,reject:f});z(d,c,e)})["catch"](f)})}},{key:"get",value:function(c){var b=this;return new v(function(d,e){return c=f(c,"get"),b.ready().then(function(){a(b,c,{resolve:d,reject:e});z(b,c)})["catch"](e)})}},
{key:"set",value:function(c,b){var d=this;return new v(function(e,g){if(c=f(c,"set"),null==b)throw new TypeError("There must be a value to set.");return d.ready().then(function(){a(d,c,{resolve:e,reject:g});z(d,c,b)})["catch"](g)})}},{key:"on",value:function(c,b){if(!c)throw new TypeError("You must pass an event name.");if(!b)throw new TypeError("You must pass a callback function.");if("function"!=typeof b)throw new TypeError("The callback must be a function.");0===e(this,"event:".concat(c)).length&&
this.callMethod("addEventListener",c)["catch"](function(){});a(this,"event:".concat(c),b)}},{key:"off",value:function(a,b){if(!a)throw new TypeError("You must pass an event name.");if(b&&"function"!=typeof b)throw new TypeError("The callback must be a function.");l(this,"event:".concat(a),b)&&this.callMethod("removeEventListener",a)["catch"](function(a){})}},{key:"loadVideo",value:function(a){return this.callMethod("loadVideo",a)}},{key:"ready",value:function(){var a=G.get(this)||new v(function(a,
c){c(Error("Unknown player. Probably unloaded."))});return v.resolve(a)}},{key:"addCuePoint",value:function(a,b){return this.callMethod("addCuePoint",{time:a,data:1<arguments.length&&void 0!==b?b:{}})}},{key:"removeCuePoint",value:function(a){return this.callMethod("removeCuePoint",a)}},{key:"enableTextTrack",value:function(a,b){if(!a)throw new TypeError("You must pass a language.");return this.callMethod("enableTextTrack",{language:a,kind:b})}},{key:"disableTextTrack",value:function(){return this.callMethod("disableTextTrack")}},
{key:"pause",value:function(){return this.callMethod("pause")}},{key:"play",value:function(){return this.callMethod("play")}},{key:"requestFullscreen",value:function(){return p.isEnabled?p.request(this.element):this.callMethod("requestFullscreen")}},{key:"exitFullscreen",value:function(){return p.isEnabled?p.exit():this.callMethod("exitFullscreen")}},{key:"getFullscreen",value:function(){return p.isEnabled?v.resolve(p.isFullscreen):this.get("fullscreen")}},{key:"requestPictureInPicture",value:function(){return this.callMethod("requestPictureInPicture")}},
{key:"exitPictureInPicture",value:function(){return this.callMethod("exitPictureInPicture")}},{key:"getPictureInPicture",value:function(){return this.get("pictureInPicture")}},{key:"unload",value:function(){return this.callMethod("unload")}},{key:"destroy",value:function(){var a=this;return new v(function(b){var c;G["delete"](a);y["delete"](a.element);a._originalElement&&(y["delete"](a._originalElement),a._originalElement.removeAttribute("data-vimeo-initialized"));a.element&&"IFRAME"===a.element.nodeName&&
a.element.parentNode&&(a.element.parentNode.parentNode&&a._originalElement&&a._originalElement!==a.element.parentNode?a.element.parentNode.parentNode.removeChild(a.element.parentNode):a.element.parentNode.removeChild(a.element));a.element&&"DIV"===a.element.nodeName&&a.element.parentNode&&(a.element.removeAttribute("data-vimeo-initialized"),(c=a.element.querySelector("iframe"))&&c.parentNode&&(c.parentNode.parentNode&&a._originalElement&&a._originalElement!==c.parentNode?c.parentNode.parentNode.removeChild(c.parentNode):
c.parentNode.removeChild(c)));a._window.removeEventListener("message",a._onMessage);b()})}},{key:"getAutopause",value:function(){return this.get("autopause")}},{key:"setAutopause",value:function(a){return this.set("autopause",a)}},{key:"getBuffered",value:function(){return this.get("buffered")}},{key:"getCameraProps",value:function(){return this.get("cameraProps")}},{key:"setCameraProps",value:function(a){return this.set("cameraProps",a)}},{key:"getChapters",value:function(){return this.get("chapters")}},
{key:"getCurrentChapter",value:function(){return this.get("currentChapter")}},{key:"getColor",value:function(){return this.get("color")}},{key:"setColor",value:function(a){return this.set("color",a)}},{key:"getCuePoints",value:function(){return this.get("cuePoints")}},{key:"getCurrentTime",value:function(){return this.get("currentTime")}},{key:"setCurrentTime",value:function(a){return this.set("currentTime",a)}},{key:"getDuration",value:function(){return this.get("duration")}},{key:"getEnded",value:function(){return this.get("ended")}},
{key:"getLoop",value:function(){return this.get("loop")}},{key:"setLoop",value:function(a){return this.set("loop",a)}},{key:"setMuted",value:function(a){return this.set("muted",a)}},{key:"getMuted",value:function(){return this.get("muted")}},{key:"getPaused",value:function(){return this.get("paused")}},{key:"getPlaybackRate",value:function(){return this.get("playbackRate")}},{key:"setPlaybackRate",value:function(a){return this.set("playbackRate",a)}},{key:"getPlayed",value:function(){return this.get("played")}},
{key:"getQualities",value:function(){return this.get("qualities")}},{key:"getQuality",value:function(){return this.get("quality")}},{key:"setQuality",value:function(a){return this.set("quality",a)}},{key:"getSeekable",value:function(){return this.get("seekable")}},{key:"getSeeking",value:function(){return this.get("seeking")}},{key:"getTextTracks",value:function(){return this.get("textTracks")}},{key:"getVideoEmbedCode",value:function(){return this.get("videoEmbedCode")}},{key:"getVideoId",value:function(){return this.get("videoId")}},
{key:"getVideoTitle",value:function(){return this.get("videoTitle")}},{key:"getVideoWidth",value:function(){return this.get("videoWidth")}},{key:"getVideoHeight",value:function(){return this.get("videoHeight")}},{key:"getVideoUrl",value:function(){return this.get("videoUrl")}},{key:"getVolume",value:function(){return this.get("volume")}},{key:"setVolume",value:function(a){return this.set("volume",a)}}],b(d.prototype,g),d}();return B||(w=function(){for(var a,b=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),
"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],
c=0,e=b.length,f={};c<e;c++)if((a=b[c])&&a[1]in document){for(c=0;c<a.length;c++)f[b[0][c]]=a[c];return f}return!1}(),F={fullscreenchange:w.fullscreenchange,fullscreenerror:w.fullscreenerror},n={request:function(a){return new Promise(function(b,c){function d(){n.off("fullscreenchange",d);b()}n.on("fullscreenchange",d);var e=(a=a||document.documentElement)[w.requestFullscreen]();e instanceof Promise&&e.then(d)["catch"](c)})},exit:function(){return new Promise(function(a,b){var c,d;n.isFullscreen?(c=
function P(){n.off("fullscreenchange",P);a()},n.on("fullscreenchange",c),(d=document[w.exitFullscreen]())instanceof Promise&&d.then(c)["catch"](b)):a()})},on:function(a,b){var c=F[a];c&&document.addEventListener(c,b)},off:function(a,b){var c=F[a];c&&document.removeEventListener(c,b)}},Object.defineProperties(n,{isFullscreen:{get:function(){return!!document[w.fullscreenElement]}},element:{enumerable:!0,get:function(){return document[w.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!document[w.fullscreenEnabled]}}}),
p=n,function(a){function b(a){"console"in window&&console.error&&console.error("There was an error creating an embed: ".concat(a))}[].slice.call((0<arguments.length&&void 0!==a?a:document).querySelectorAll("[data-vimeo-id], [data-vimeo-url]")).forEach(function(a){try{if(null===a.getAttribute("data-vimeo-defer")){var c=x(a);I(h(c),c,a).then(function(b){return D(b,a)})["catch"](b)}}catch(O){b(O)}})}(),function(a){var b=0<arguments.length&&void 0!==a?a:document;window.VimeoPlayerResizeEmbeds_||(window.VimeoPlayerResizeEmbeds_=
!0,window.addEventListener("message",function(a){if(k(a.origin)&&a.data&&"spacechange"===a.data.event)for(var c=b.querySelectorAll("iframe"),d=0;d<c.length;d++)if(c[d].contentWindow===a.source){c[d].parentElement.style.paddingBottom="".concat(a.data.data[0].bottom,"px");break}}))}()),E});
